### PR TITLE
Move assertion messages into code and deprecate AssertionError

### LINKED ISSUE #14028: v7.0.0 assertion urls lead to 404
**Describe the bug**
v7.0.0 assertion urls lead to 404

**To Reproduce**
https://codesandbox.io/s/vector-tile-info-forked-5511r5 shows https://openlayers.org/en/v7.0.0/doc/errors/#68 which is a 404.

**Expected behavior**
Valid urls

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #14028.

I think it's best to keep the same codes for now, even though some are duplicated, in case anyone relies on them. And to deprecate `ol/AssertionError` in favor of throwing plain `Error`s instead, starting with the next major version. What do others think?

### CODE REVIEW

**Review by tschaub — APPROVED** [review]

File: src/ol/AssertionError.js [hunk 1]
```diff
@@ -13,13 +72,7 @@ class AssertionError extends Error {
...
    */
   constructor(code) {
-    const path = VERSION === 'latest' ? VERSION : 'v' + VERSION.split('-')[0];
-    const message =
-      'Assertion failed. See https://openlayers.org/en/' +
-      path +
-      '/doc/errors/#' +
-      code +
-      ' for details.';
+    const message = `Assertion failed. ${messages[code]}.`;
```
Comment (tschaub) [inline src/ol/AssertionError.js:75]: I'd be in favor of simplifying this to just `messages[code]`.  I think the "Assertion failed" part of the message isn't meaningful and potentially confusing to users.

File: changelog/upgrade-notes.md [hunk 2]
```diff
@@ -2,6 +2,12 @@
 
 ### Next version
 
+#### Deprecation of `ol/AssertionError` and error codes
+
+Future versions will no longer throw `ol/AssertionError` with an error `code`. Instead, they will throw `Error` with just the error message.
+
+### v7.0.0
+
```
Comment (tschaub) [inline changelog/upgrade-notes.md:10]: This file looks out of date

**Review by tschaub — APPROVED** [review]
Thanks, @ahocevar

File: changelog/upgrade-notes.md (hunk 2 above)
Comment (ahocevar) [reply changelog/upgrade-notes.md:19]: Indeed. I just rebased the pull request.
