### PR TITLE
Rework TileDebug to allow TMS coordinates and to fix reprojection

### LINKED ISSUE #12361: Tiledebug layer and TileImage layer with inverted y {-y}
**Describe the bug**
TileDebug do not represent the inverted -y coordinate for tileimage layer. 

**To Reproduce**
1. Go to 'https://geoegl.msp.gouv.qc.ca/igo2/mtq-test/?context=tile_debug&sidenav=1&tool=mapTools' 
2. In the Network console (F12), the call made to the TileImage server do not correspond to the tile debug coordinates in Y. 
3. here the layer definition
````
TileDebug
       {
            "title": "tiledebug",
            "visible": true,
            "sourceOptions": {
                "type": "tiledebug"
            }
        },
TileImage
        {
            "baselayer: "baselayer",
            "sourceOptions": {
                "url": "/service@EPSG_3857/{z}/{x}/{-y}.png",
                "type": "xyz"
            }
        }
````

**Expected behavior**
How handle a tiledebug layer with an inverted Y coordinate ( {-y} ) without having to define a custom tilegrid?
image

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #12361 and #12363

Rework `ol/source/TileDebug` to fix reprojection.  This is much more closely based on `ol/source/XYZ` and adds a `setImage()` method to the `ol/ImageTile` class to allow a canvas or preloaded image to be set directly by a `tileLoadFunction`.  Also add a template option to TileDebug which will allow custom tile coordinates such as TMS to be displayed.

Add new example showing debug tiles for a TMS vector tile source.

Add rendering test for reprojection.

Resolve a timing issue in `ol/reproj/Tile` to allow `ol/ImageTile.setImage` to work synchronously and maintain performance similar to previous TileDebug implementation.

Add option to show the OSM tile coordinates in the Reprojection with EPSG.io Search example.

### CODE REVIEW

**Review by ahocevar — CHANGES_REQUESTED** [review]
Also, instead of adding to existing examples, please create a new example that shows how to use the template option, and a rendering test to ensure reprojection works properly.

For easier reviewing, could you please either split this pull request into separate commits for the four separate things you changed, or add comments to your changes to hint the reviewer?

**Review by ahocevar — APPROVED** [review]
Very slick. Great work @mike-000. Thanks!

File: src/ol/ImageTile.js [hunk 1]
```diff
@@ -72,6 +72,18 @@ class ImageTile extends Tile {
     return this.image_;
   }
 
+  /**
+   * Sets an HTML image element for this tile (may be a Canvas or preloaded Image).
+   * @param {HTMLCanvasElement|HTMLImageElement} element Element.
+   * @api
```
Comment (ahocevar) [inline src/ol/ImageTile.js:78]:
```suggestion
```
