### PR TITLE
Use appropriate UNPACK_ALIGNMENT for data textures

### LINKED ISSUE #12995: Black tiles with DataTileSource and WebGLTileLayer
**Describe the bug**

The`ol.layer.WebGLTile` doesn't render data that were loaded with `ol.source.DataTile` using a custom tile grid:

Extent: `[0, -23828, 23903, 0]`
Sizes: `[[1, 1], [7, 7], [ 25, 25 ], [100, 100]]`
Tile sizes: `[[770, 768], [240, 240], [240, 240], [240, 240]]`

Screen Shot 2021-11-12 at 10 00 32 PM

The following warning message gets logged:

```
WebGL warning: texImage: Desired upload requires more data than is available: (767 rows plus 770 pixels needed, 767 rows plus 258 pixels available)
```

I didn't previously experience this issue and wonder whether it may be due to either https://github.com/openlayers/openlayers/pull/11532 or https://github.com/openlayers/openlayers/pull/12024.

**Expected behavior**

Not sure whether this is a bug or whether my understanding of the tile grid is wrong.

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #12995

Most of the time (RGBA data and/or standard tile sizes) the default `UNPACK_ALIGNMENT` value of 4 has no problems.   However a combination of RBG or other data and non-standard tile sizes may mean this does not work.  The calculations assumed an `UNPACK_ALIGNMENT` of 1 (not a valid assumption) but continued to use the default value,  It is possible to avoid assumptions and calculate an appropriate value from the data `size` and `byteLength` and set that when uploading data textures, then restore the default value.  It should not be necessary for the application to guess a value and patch it in the prerender event.

### CODE REVIEW

**Comment by mike-000** [comment]
I used a modified version of the Data Tiles examples https://codesandbox.io/s/data-tiles-forked-yx559?file=/main.js to check the calculations work - it could be used as the basis for rendering tests if needed.

File: src/ol/webgl/TileTexture.js [hunk 1]
```diff
@@ -84,6 +93,7 @@ function uploadDataTexture(helper, texture, data, size, bandCount) {
     textureType,
     data
   );
+  gl.pixelStorei(gl.UNPACK_ALIGNMENT, 4);
```
Comment (tschaub) [inline src/ol/webgl/TileTexture.js]: We can restore this to the previous `gl.getParameter(gl.UNPACK_ALIGNMENT)` value.  I've changed this in the latest commit.

File: src/ol/webgl/TileTexture.js [hunk 2]
```diff
@@ -36,8 +36,16 @@ function uploadImageTexture(gl, texture, image) {
...
+ * @param {number} unpackAlignment The unpack alignment.
  */
-function uploadDataTexture(helper, texture, data, size, bandCount) {
+function uploadDataTexture(
+  helper,
+  texture,
+  data,
+  size,
+  bandCount,
+  unpackAlignment
```
Comment (tschaub) [inline src/ol/webgl/TileTexture.js]: Instead of adding another argument, this function can determine the optimal unpack alignment based on `data.byteLength / size[1]`.  I've changed this in the latest commit.

**Comment by tschaub** [comment]
Thanks for identifying this issue and putting together a fix, @mike-000.

I think it is worth describing two separate issues that your change addresses.

The first issue is with texture data where the "byte width" (or number of bytes per row) is not a power of two.  This is the issue described in #12995 (e.g. 3-band, 8-bit data and a tile width of 25).  This can be addressed by setting the appropriate `gl.UNPACK_ALIGNMENT`.

The second change you've made here is to allow "loosely packed" data tiles (where the band count x tile width x tile height is not the same as the length of the data array).  I'm not sure when we might encounter these.  But I think it makes sense to respect the provided tile width (and height) in this case.

I've added rendering tests for these two separate cases and reworked the alignment handling a bit.

**Review by tschaub — APPROVED** [review]
