### PR TITLE
Defer ZoomSlider initialization until its size is available

### LINKED ISSUE #11104: ZoomSlider initializaion wrong when not visible when added
**Describe the bug**
When the ZoomSlider element is added to the map and the map and/or the ZoomSlider are not displayed the element size evaluates to 0x0 and this is never corrected. 

**To Reproduce**
1. Go to https://codesandbox.io/s/zoomslider-init-kgl9o
2. The zoomslider is initially not displayed with css and will become visible after 1sec
3. The slider element is not usable because the calculated height is zero

**Expected behavior**
Do not initialize the slider when its size is not yet available.

### PR DESCRIPTION
**Pull request by M393**
Fixes #11104

### CODE REVIEW

File: src/ol/control/ZoomSlider.js [hunk 1]
```diff
@@ -366,8 +368,8 @@ class ZoomSlider extends Control {
     if (!mapEvent.frameState) {
       return;
     }
-    if (!this.sliderInitialized_) {
-      this.initSlider_();
+    if (!this.sliderInitialized_ && !this.initSlider_()) {
+      return;
```
Comment (ahocevar) [inline src/ol/control/ZoomSlider.js:372]: The slider can still get out of sync with the map, e.g. when a view with different resolution settings is assigned to the map.
