### PR TITLE
Render vector tile image with correct resolution

### LINKED ISSUE #17034: Tiles do not load consistently after View.animate()
**Describe the bug**
When we use `View.animate()` to change the center and zoom, several tiles remain unloaded after animation is finished. 

We're observing this bug in **Chrome v139** on Windows, but not in **Firefox v141** on Windows. Have not tested other browsers or OSes.

Image

**To Reproduce**

<details>
<summary>HTML page for minimal reproduction</summary>

```
<!doctype html>
<html lang="en">

<head>
  <title>OpenLayers tile animate issue</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body,
    #map {
      bottom: 0;
      margin: 0;
      padding: 0;
      position: absolute;
      left: 0;
      right: 0;
      top: 0;
    }

    #zoom-out-button {
      bottom: 0;
      position: absolute;
    }
  </style>
</head>

<body>
  <div id="map"></div>
  <button id="zoom-out-button">Zoom out</button>
  <script src="https://cdn.jsdelivr.net/npm/ol@v10.6.1/dist/ol.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/ol-mapbox-style@v13.1.0/dist/olms.js"></script>
  <script type="module">
    const view = new ol.View({
      center: [1153181, 9206077],
      zoom: 15
    });
	
	const openfreemap = new ol.layer.Group();
    const map = new ol.Map({
	  layers: [openfreemap],
      target: document.getElementById('map'),
      view
    });

	olms.apply(openfreemap, 'https://tiles.openfreemap.org/styles/liberty');

    document.getElementById('zoom-out-button').addEventListener('click', () => {
      view.animate({ center: [1157232, 9197946], zoom: 5 });
    });
  </script>
</body>

</html>
```

</details>

1. Load the page

Image

2. Click 'Zoom out' in the bottom-left corner, which calls `view.animate({ center: [1157232, 9197946], zoom: 5 });`
3. See that some tiles (typically near the center of the view) have failed to load:

Image

**Expected behavior**

All tiles should have loaded:

Image

**Additional information**

- There are no HTTP errors in the network log, no trace of requests failing or being interrupted.

Image

- This bug does not occur in OpenLayers v9.2.4

```
<script src="https://cdn.jsdelivr.net/npm/ol@v9.2.4/dist/ol.js"></script>
```

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #17034 

The problem was that the `wantedResolution` may be set to a resolution outside of the valid range of the tile. The solution is to only use the exact view resolution when rendering in hifi mode, when the tile within its resolution range. Otherwise the nominal tile resolution is used.

### CODE REVIEW

File: src/ol/renderer/canvas/VectorTileLayer.js [hunk 1]
```diff
@@ -919,10 +926,10 @@ class CanvasVectorTileLayerRenderer extends CanvasTileLayerRenderer {
     const replayState = tile.getReplayState(layer);
     const revision = layer.getRevision();
     const resolution = tile.wantedResolution;
-    return (
+    const tileImageNeedsRender =
       replayState.renderedTileResolution !== resolution ||
-      replayState.renderedTileRevision !== revision
-    );
+      replayState.renderedTileRevision !== revision;
+    return tileImageNeedsRender;
```
Comment (ahocevar) [inline src/ol/renderer/canvas/VectorTileLayer.js:932]: Not a functional change - the extra variable assignment was necessary for easier debugging, and I decided to keep it for better code readability.

**Review by tschaub — APPROVED** [review]

**Comment by ahocevar** [comment]
Thanks for the review, @tschaub
