### PR TITLE
Do not assert null projection

### LINKED ISSUE #13564: TypeError when showing Cloud Optimized GeoTiffs (COG) without georeference
**Describe the bug**
Hi, I want to use biological TIFFs on this phenomenal package. Those obviously do not have georeference data. I stumbled upon #12701 and tried running the working example verbatim. The map did show up but was not smooth. In the console, I found a barrage of this error.

```
Uncaught TypeError: projection1 is null
    equivalent proj.js:443
    getTileCacheForProjection Tile.js:285
    expireCache Tile.js:154
    postRenderFunction TileLayer.js:653
    handlePostRender PluggableMap.js:1220
    postRenderTimeoutHandle_ PluggableMap.js:1602
    setTimeout handler*PluggableMap2.prototype.renderFrame_ PluggableMap.js:1600
    animationDelay_ PluggableMap.js:260
    render PluggableMap.js:1435
    handleTileChange_ chunk-SSSZKFIN.js:2477
    handleTileChange chunk-SSSZKFIN.js:1968
    dispatchEvent Target.js:114
    changed Tile.js:139
    load DataTile.js:86
    promise callback*DataTile2.prototype.load DataTile.js:83
    loadMoreTiles chunk-SSSZKFIN.js:1982
    handlePostRender chunk-SSSZKFIN.js:2401
    postRenderTimeoutHandle_ PluggableMap.js:1602
    setTimeout handler*PluggableMap2.prototype.renderFrame_ PluggableMap.js:1600
    animationDelay_ PluggableMap.js:260
    render PluggableMap.js:1435
    dispatchEvent Target.js:114
    changed Observable.js:70
    handleLayerChange_ Group.js:149
    dispatchEvent Target.js:114
    changed Observable.js:70
    handleSourceChange_ Layer.js:223
    dispatchEvent Target.js:114
    changed Observable.js:70
    setState Source.js:215
    configure_ GeoTIFF.js:621
    GeoTIFFSource2 GeoTIFF.js:417
    promise callback*GeoTIFFSource2 GeoTIFF.js:416

```

Ran on OpenLayers 6.14.1

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #13564

Source and view projections must be equivalent, but for GeoTIFF null is valid and equivalent to view projection.

### CODE REVIEW

File: src/ol/source/Tile.js [hunk 1]
```diff
@@ -281,8 +281,9 @@ class TileSource extends Source {
    * @protected
    */
   getTileCacheForProjection(projection) {
+    const sourceProjection = this.getProjection();
```
Comment (ahocevar) [inline src/ol/source/Tile.js:284]: While at it, you could add `|null` as return type for `ol/Source#getProjection()`.

**Review by ahocevar — CHANGES_REQUESTED** [review]

**Review by ahocevar — APPROVED** [review]
