### PR TITLE
Make Select interaction work when there are multiple instances

### LINKED ISSUE #10501: Multiple select interactions on same features corrupt style
**Describe the bug**
It is not possible to have more than one select interaction activated on the same set of features. The select style is mistaken for the default style with the second interaction.

This has the same root cause as https://github.com/openlayers/openlayers/issues/10486, but is not solved by that fix.

**To Reproduce**
Have 2 select interactions on the same layer. E.g. one for click (`condition: ol.events.condition.click`) and one for hover (`condition: ol.events.condition.pointerMove`).

**Expected behavior**
When the pointer moves over the feature, it should get the selected style and when the pointer moves away, it should acquire the unselected style again.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #10501

### CODE REVIEW

File: src/ol/interaction/Select.js [hunk 1]
```diff
@@ -345,28 +343,44 @@ class Select extends Interaction {
...
    * @param {import("../Feature.js").default} feature Feature
    * @private
    */
-  removeSelectedStyle_(feature) {
+  restorePreviousStyle_(feature) {
     const key = getUid(feature);
-    feature.setStyle(this.featureStyleAssociation_[key]);
-    delete this.featureStyleAssociation_[key];
+    const selectInteractions = /** @type {Array<Select>} */ (this.getMap().getInteractions().getArray().filter(function(interaction) {
+      return interaction instanceof Select && interaction.getFeatures().getArray().indexOf(feature) !== -1;
```
Comment (michalzielanski) [inline src/ol/interaction/Select.js]: Thanks @ahocevar for this PR. It seems to me that the filter condition should check if the feature has style.
```javascript
return interaction instanceof Select && interaction.getStyle() && interaction.getFeatures().getArray().indexOf(feature) !== -1;
```

Comment (ahocevar) [reply src/ol/interaction/Select.js]: @michalzielanski `interaction.getStyle() !== false` to be precise:

> `style`: Style for the selected features. By default the default edit style is used (see module:ol/style). If set to false the selected feature's style will not change.

Can you create a follow-up pull request?

Comment (michalzielanski) [reply src/ol/interaction/Select.js]: In other places there is no strong type checking. There is only `if (this.style_)`, so `null` instead of `false` will also work. Using `interaction.getStyle() !== false` only here will cause a malfunction if someone uses `null` instead of `false`.
Creating PR would take me half a day, you will do it quicker :)

Comment (ahocevar) [reply src/ol/interaction/Select.js]: See #10708. Feel free to buy me a beer @michalzielanski ;-)

Comment (michalzielanski) [reply src/ol/interaction/Select.js]: :)
