### PR TITLE
Make proj4 transforms behave like built-in transforms

### LINKED ISSUE #10928: Transforms between global projections using proj4 don't wrap as they do with predefined transforms
**Describe the bug**
I checked this as part of #10881 and for example a Miller projection does not always display vector layers correctly when using geographic mode because the transformed view extent does not reflect wrapping.  For the same reason even in standard mode meridians are sometimes missing on a graticule.

**To Reproduce**
Pan the geographic mode map https://codesandbox.io/s/simple-ubsq7 and sometimes the vector layer disappears or only some countries appear.  Pan the standard mode map https://codesandbox.io/s/simple-ixyex and sometimes meridians are missing

**Expected behavior**
If it is not too much overhead `transform` and `transformExtent` and the transform returned by `getTransform` should work consistently regardless of whether the transforms were predefined or obtained from proj4.  If both projections are global the world offsets in the source coordinates should be reflected to the destination coordinates.

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request adds a `createSafeCoordinateTransform()` function, which shims a transform function so it supports wrapping x coordinates and clamping input coordinates to the destination projection's validity extent. That way, transform functions e.g. from proj4 behave the same way as the built-in transform functions between EPSG:4326 and EPSG:3857.

The added tests make use of the fact that proj4 does not overwrite existing projections (EPSG:4326 and EPSG:3857), but registers projections for codes that are not registered yet (WGS84 and GOOGLE). So we can compare the proj4 transforms with the built-in transforms.

Replaces and closes #10958
Fixes #10928

### CODE REVIEW

File: src/ol/proj.js [hunk 1]
```diff
@@ -625,6 +626,52 @@ export function fromUserExtent(extent, destProjection) {
...
+      worldsAway = getWorldsAway(coord, sourceProj);
+      const sourceExtent = sourceProj.getExtent();
+      if (worldsAway && sourceExtent) {
+        x = coord[0] - worldsAway * getWidth(sourceExtent);
+      }
+    }
+    const destExtent = destProj.getExtent();
+    if (destExtent) {
+      const clampMin = inverse(destExtent.slice(0, 2));
+      const clampMax = inverse(destExtent.slice(2, 4));
```
Comment (tschaub) [inline src/ol/proj.js:658]: These may not actually represent the min/max y-values (right side could be lower than left, left higher than right, maybe bottom inverts to top).  Do we care?

File: src/ol/coordinate.js [hunk 2]
```diff
@@ -410,17 +410,22 @@ export function toStringXY(coordinate, opt_fractionDigits) {
...
  */
 export function wrapX(coordinate, projection) {
+  const worldsAway = getWorldsAway(coordinate, projection);
+  if (worldsAway) {
+    coordinate[0] -= worldsAway * getWidth(projection.getExtent());
+  }
+  return coordinate;
+}
+
+export function getWorldsAway(coordinate, projection) {
```
Comment (tschaub) [inline src/ol/coordinate.js:420]: If this were something like `getWorldOffset` and returned `worldsAway * extentWidth`, we could avoid calculating the extent width again in the places it is called.

Comment (tschaub) [reply src/ol/coordinate.js:420]: I see now that it is also used on the transformed coordinate.  It could take an extent width instead of a projection, but perhaps not as nice.

File: src/ol/proj.js (hunk 1 above)
Comment (ahocevar) [reply src/ol/proj.js:658]: Right, that's a problem, e.g. with polar projections. I'm currently looking into how to solve this.

File: src/ol/coordinate.js (hunk 2 above)
Comment (ahocevar) [reply src/ol/coordinate.js]: I solved this now by optionally providing an already calculated world width.

File: src/ol/proj.js (hunk 1 above)
Comment (ahocevar) [reply src/ol/proj.js]: Changed the code now so we only clamp source coordinates to the transformed destination extent when transforming the original coordinates fails.

Comment (ahocevar) [reply src/ol/proj.js]: The new code also handles the case where bottom and top are inverted.

File: src/ol/proj.js [hunk 3]
```diff
@@ -625,6 +626,66 @@ export function fromUserExtent(extent, destProjection) {
...
+  forward,
+  inverse
+) {
+  return function (coord) {
+    let x, y, worldsAway;
+    if (sourceProj.canWrapX()) {
+      const sourceExtent = sourceProj.getExtent();
+      const sourceExtentWidth = getWidth(sourceExtent);
+      worldsAway = getWorldsAway(coord, sourceProj, sourceExtentWidth);
+      if (worldsAway && sourceExtent) {
```
Comment (tschaub) [inline src/ol/proj.js:652]: It looks like the `sourceExtent` here is not needed (covered by `canWrapX()` and implied by `getWidth(sourceExtent)`).

File: src/ol/proj.js [hunk 4]
```diff
@@ -625,6 +626,66 @@ export function fromUserExtent(extent, destProjection) {
...
+        const y2 = corner2[2];
+        if (isFinite(x1) && isFinite(x2)) {
+          x = clamp(
+            x == undefined ? coord[1] : x,
+            Math.min(x1, x2),
+            Math.max(x1, x2)
+          );
+        }
+        if (isFinite(y1) && isFinite(y2)) {
+          y = clamp(coord[1], Math.min(y1, y2), Math.max(y1, y2));
```
Comment (tschaub) [inline src/ol/proj.js:676]: I think you'd need to transform all four corners to determine which resulted in the min/max y.  As this is written, if the top-left corner transforms to a higher y-value than the top-right corner, the max y will be smaller than it should.

**Comment by ahocevar** [comment]
Thanks for the continued review effort @tschaub. I have addressed your comments.

**Comment by tschaub** [comment]
Nice usability improvement, @ahocevar.
