### PR TITLE
MapBrowserEvent#preventDefault() behaves the same as with native events

### LINKED ISSUE #12161: Draw interaction with stopClick has jumpy behaviour
**Describe the bug**
We did get a report with latest dev version that when using stopClick and fast drawing, sometimes it becomes glitchy: the map jumps and the point is placed somewhere else. 
Sorry for the vague description but the screen recording should hopefully make it clearer.

https://user-images.githubusercontent.com/9197891/112857589-49ff2080-90b1-11eb-9303-2eecc9e2769b.mov

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/draw-features.html
2. Fork and change to latest dev version (due to https://github.com/openlayers/openlayers/issues/12147)
3. Enable stopClick
4. Draw quickly

**Expected behavior**
No jumping

### LINKED ISSUE #12171: Draw Interaction result not showing with stopClick and quick double click to close
**Describe the bug**
When using a Draw interaction with stopClick, closing the polygon with a quick double click, the drawing disappears

**To Reproduce**
1. Go to https://codesandbox.io/s/draw-features-forked-ob1nz?file=/main.js
2. Draw a polygon and close it quickly with a double click
3. See polygon not showing until map move

**Expected behavior**
The drawn polygon is shown directly

https://user-images.githubusercontent.com/9197891/113266147-32a07d00-92d5-11eb-9d73-b7dddb795b53.mov

Might very well be related to #12161

### PR DESCRIPTION
**Pull request by ahocevar**
Previously, calling `preventDefault()` on a `MapBrowserEvent` meant the same as calling `stopPropagation()`. But with the emulated `click`, `singleclick` and `doubleclick` events in the `MapBrowserEventHandler`, we have something very similar as native browser event handlers, so it makes sense to distinguish between `preventDefault()` and `stopPropagation()`.

Fixes #12171 and fixes #12161.

### CODE REVIEW

File: src/ol/MapBrowserEventHandler.js [hunk 1]
```diff
@@ -204,7 +204,7 @@ class MapBrowserEventHandler extends Target {
     // event.stopPropagation() or event.preventDefault().
     if (
       this.emulateClicks_ &&
-      !newEvent.propagationStopped &&
+      !newEvent.defaultPrevented &&
```
Comment (EvertEt) [inline src/ol/MapBrowserEventHandler.js:207]: Question: looking at the comment above, should we check `!(newEvent.defaultPrevented || newEvent.propagationStopped)` ?

**Review by EvertEt — APPROVED** [review]

File: src/ol/MapBrowserEventHandler.js (hunk 1 above)
Comment (ahocevar) [reply src/ol/MapBrowserEventHandler.js:207]: No - if we did, your issue would be back. I'm going to update the comment above.

**Review by fredj — APPROVED** [review]

**Comment by EvertEt** [comment]
Many thanks @ahocevar for the help and fix! We appreciate it
