### PR TITLE
Don't use HTMLImageElement.decode method on Safari

### LINKED ISSUE #9628: Icons in mapbox-vector-tiles example broken
The icons in the [mapbox-vector-tiles.html](https://openlayers.org/en/master/examples/mapbox-vector-tiles.html) examples, which should appear at high zoom levels, are no longer drawn.

`git bisect` shows that 2e34dd0fafdc40a0bdd2023db55514083b1da87c is the first bad commit.

/cc @fredj

### PR DESCRIPTION
**Pull request by fredj**
The decode function is supported by Safari but not when the image is a svg file.
Upstream bug report: https://bugs.webkit.org/show_bug.cgi?id=198527

fixes #9628

### CODE REVIEW

File: src/ol/Image.js [hunk 1]
```diff
@@ -157,7 +158,10 @@ class ImageWrapper extends ImageBase {
  */
 export function listenImage(image, loadHandler, errorHandler) {
   const img = /** @type {HTMLImageElement} */ (image);
-  if (img.decode) {
+
+  // The decode function is supported by Safari but not when the image is a svg file.
+  // FIXME: remove `!SAFARI` in the test when this bug is fixed upstream.
```
Comment (tschaub) [inline src/ol/Image.js]: It could be useful to link to the bug here.
