### PR TITLE
Only peek tiles we're not sure we're going to use

### LINKED ISSUE #16508: Infinite reloading of a tile
**Infinite reloading of a tile**
With incorrect vector tile url OpenLayers tries to reload tile indefinitely.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a html with the source provided below
2. Zoom until 7 level
3. Network traffic shows infinite reloading of vector tiles (which all produce 404).

**Expected behavior**
If tile request gets 404 there is no point to retry.
**Note:** error is not reproducible with say 10.2.1 version.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple OpenLayers Map</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@latest/ol.css">
    <style>body { margin: 0; padding: 0; } #map { width: 100%; height: 100vh; }</style>
</head>
<body>
    <div id="map"></div>

    <script src="https://cdn.jsdelivr.net/npm/ol@latest/dist/ol.js"></script>
    <script>
        const map = new ol.Map({
            target: 'map',
            layers: [
                new ol.layer.Tile({ source: new ol.source.OSM() }),
                new ol.layer.VectorTile({
                    source: new ol.source.VectorTile({
                        format: new ol.format.MVT(),
                        url: 'https://something.bad/{z}/{x}/{y}.pbf'
                    }),
                    style: new ol.style.Style()
                })
            ],
            view: new ol.View({
                center: ol.proj.fromLonLat([0, 0]), // Center of the map [longitude, latitude]
                zoom: 2 // Initial zoom level
            })
        });
    </script>
</body>
</html>
```

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #16508.

The problem is that `TileCache#get()` marks a tile as used, and when looking for alt or stale tiles we're not sure we're actually going to use them. But marking stale and alt tiles as newer can result in actually needed tiles to get purged from the cache. So I changed those call sites of `TileCache#get()` to `TileCache#peek()`, which does not mark the tiles as used in the cache.

### CODE REVIEW

File: src/ol/source/VectorTile.js [hunk 1]
```diff
@@ -300,6 +300,7 @@ class VectorTile extends UrlTile {
       this.tileKeysBySourceTileUrl_[sourceTileUrl].splice(index, 1);
       if (this.tileKeysBySourceTileUrl_[sourceTileUrl].length === 0) {
         delete this.tileKeysBySourceTileUrl_[sourceTileUrl];
+        this.sourceTiles_[sourceTileUrl].dispose();
```
Comment (ahocevar) [inline src/ol/source/VectorTile.js:303]: Not strictly related, but during debugging I found that we're not disposing of source tiles, so I added that.

File: src/ol/Tile.js [hunk 2]
```diff
@@ -172,7 +172,11 @@ class Tile extends EventTarget {
    * @api
    */
   setState(state) {
-    if (this.state !== TileState.ERROR && this.state > state) {
+    if (
+      this.state !== TileState.ERROR &&
+      this.state !== TileState.EMPTY &&
```
Comment (ahocevar) [inline src/ol/Tile.js:177]: When a tile has an `EMPTY` state, we don't really care about the state sequence, because the change to `EMPTY` that happens before has cleared the listeners on the `TileQueue` already.

I added this commit because the previous "not strictly related change" made a test fail-

**Comment by ahocevar** [comment]
Changed pull request to only contain the changes mentioned in the title. I'm going to make the other changes in a separate pull request.

**Review by jahow — APPROVED** [review]
Thanks! Maybe we should come up with one or two rendering tests covering these intricate tile loading behaviors? I feel like it's hard to be sure that it will end up working as intended for the user with unit tests alone

**Comment by ahocevar** [comment]
Thanks for the review, @jahow . How would you envision a rendering test for that to look? The visual behavior does not change, it's a matter of infinitely creating new tiles vs. using what's in the cache.

**Comment by jahow** [comment]
I'm not 100% sure but maybe we can come up with a data tile layer that draws on each tile the relevant tile information (state eg. loaded/error/stale, amount of time requested...) and then move around a bit to trigger various parts of the tile cache logic. Then we can test visually that the underlying state of the tiles is correct.
