### PR TITLE
getExtent() to return getEmpty() if geometry is unprojectable

### LINKED ISSUE #11175: ol/geom/Geometry#getExtent() should return createEmpty() if geometry contains NaN coordinates
**Describe the bug**
Coordinates are quite reasonably transformed to NaN if they are impossible for the projection (e.g. the opposite side of the world in an orthographic projection).  However if any coordinate in any feature is NaN the entire layer fails to render as the geometry extent, and consequently the vector source extent, is returned as [NaN, NaN, NaN, NaN].  A simple fix would be for ol/geom/Geometry#getExtent() to return an empty extent if invalid.  https://codesandbox.io/s/orthographic-2e8vl

ol/layer/Graticule is also failing in an orthographic projection and may need to validate further.

**To Reproduce**
See https://codesandbox.io/s/orthographic-2e8vl for a patched example which displays visible countries correctly.  Remove the patch and reload to see the problem.

**Expected behavior**
Out-of-range features should not affect rendering of in-range features.

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #11175

Return getEmpty() if unprojectable geometry coordinates have been correctly transformed to NaN to prevent the entire source extent being "tainted" and to allow projectable features to be rendered.

### CODE REVIEW

File: src/ol/geom/Geometry.js [hunk 1]
```diff
@@ -170,6 +175,14 @@ class Geometry extends BaseObject {
...
     if (this.extentRevision_ != this.getRevision()) {
       this.extent_ = this.computeExtent(this.extent_);
+      if (
+        !containsExtent(
+          [-Infinity, -Infinity, Infinity, Infinity],
+          this.extent_
+        )
+      ) {
+        this.extent_ = createEmpty();
+      }
```
Comment (ahocevar) [inline src/ol/geom/Geometry.js:185]:
```suggestion
      const extent = this.computeExtent(this.extent_);
      if (extent[0] === NaN || extent[1] === NaN) {
        createOrUpdateEmpty(extent);
      }
```
would be more efficient and create less garbage.

Comment (mike-000) [reply src/ol/geom/Geometry.js]: done
(although `=== NaN` doesn't work as `NaN === NaN` returns false)

Comment (ahocevar) [reply src/ol/geom/Geometry.js]: Right, sorry for that. I meant `isNaN(extent[0])`
