### PR TITLE
Fix #9510: EsriJSON readGeometry should not mutate input

### LINKED ISSUE #9510: EsriJSON readGeometry mutate input
**Describe the bug**
Hello,
I read geometry from Esri back-end using EsriJSON `readGeometry()` function.

I found that the original geometry was modified (either by reading the geometry again or by a read only error message from `deep-freeze`).

We observe mutating code in `EsriJSON.js` : [l.259](https://github.com/openlayers/openlayers/blob/master/src/ol/format/EsriJSON.js#L259), [l.262](https://github.com/openlayers/openlayers/blob/master/src/ol/format/EsriJSON.js#L262) among others.

**Expected behavior**
The input geometry should not be mutated.

**Workaround**
I clone the input geometry, but I find it dirty.

### PR DESCRIPTION
**Pull request by kekel87**
Fix: #9510

### CODE REVIEW

File: src/ol/format/EsriJSON.js [hunk 1]
```diff
@@ -256,10 +256,10 @@ function readGeometry(object, opt_options) {
     const rings = convertRings(esriJSONPolygon.rings, layout);
     if (rings.length === 1) {
       type = GeometryType.POLYGON;
-      object['rings'] = rings[0];
+      object = Object.assign({}, object, {rings: rings[0]});
```
Comment (tschaub) [inline src/ol/format/EsriJSON.js]: The `rings` property was quoted here to stop minifiers from renaming it.  It could be worth validating that this is still necessary, but without doing that validation, I would suggest leaving it quoted.

Comment (kekel87) [reply src/ol/format/EsriJSON.js]: That's good, I put quotes.

**Comment by tschaub** [comment]
Thanks @kekel87.
