### PR TITLE
Set label text for Graticule option styles

### LINKED ISSUE #10092: Graticule doesn't display label when using custom label style
**Describe the bug**
Graticule doesn't display label when using custom label style

**To Reproduce**

Use Graticule, notice that labels are shown. Add LabelStyle, refresh, and notice that labels don't show at all. E.g.
```
new Graticule({
    lonLabelStyle: new Text({
        font: '12px Calibri,sans-serif',
        textAlign: 'start',
        textBaseline: 'bottom',
        fill: new Fill({
            color: 'rgba(0,0,0,1)',
        }),
        stroke: new Stroke({
            color: 'rgba(255,255,255,1)',
            width: 3,
        }),
    }),
}),
```

I checked source and it it suspicious that `text: label` is not passed anywhere when custom style is used [here](https://github.com/openlayers/openlayers/blob/master/src/ol/layer/Graticule.js#L337).

**Expected behavior**
Either apply custom style, or remove config value.

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #10092

Set label text for lonLabelStyle and latLabelStyle options

### CODE REVIEW

File: src/ol/layer/Graticule.js [hunk 1]
```diff
@@ -379,6 +378,7 @@ class Graticule extends VectorLayer {
                 })
               })
           });
+          this.latLabelStyleCache_[label].getText().setText(label);
```
Comment (ahocevar) [inline src/ol/layer/Graticule.js]: With this addition, it is no longer necessary to cache or clone the style.

You could remove the `lonLabelStyleCache_` and `latLabelStyleCache_` members entirely, and create `lonLabelStyle_` and `latLabelStyle_` members instead, which either get the provided `options.lonLabelStyle` and `options.latLabelStyle` assigned, or the default that's created when these are not provided.

Comment (mike-000) [reply src/ol/layer/Graticule.js]: Yes, I had the same thought but concentrated on the minimum change to fix the bug.  I have kept a single clone of each style we are updating to guard against the possibility of a user using the supplied definition elsewhere.
