### PR TITLE
ScaleLine fix for non-degree based units

### LINKED ISSUE #7907: Wrong ScaleLine calculation for non-degree based maps with Imperial-like units
When the map is non-degree based (such as a Zoomify scanned document) the pointResolution calculation is wrong in ScaleLine.js, when using Imperial-like units.

The problem is with this lines:
https://github.com/openlayers/openlayers/blob/85d4642450a1f9bebb0e0280fd20dcf78cfca5cb/src/ol/control/ScaleLine.js#L182-L184

The correct behaviour should be to always run
```
pointResolution *= projection.getMetersPerUnit();
```
when `projection.getUnits() != Units.DEGREES`.

That is, the correct fix is to remove 
```
&& units == ScaleLineUnits.METRIC
``` 

from the condition.

This is only happening on non-degree based maps when using Imperial-like units, which must be quite a niche.

If needed, I can make an example code, but it should be logical to see why this is the case. I can also submit a PR.

### PR DESCRIPTION
**Pull request by hyperknot**
I'm thinking of possibly using `[FEET, METERS, USFEET]` instead for `projection.getUnits()` test, it's not yet clear which is the right solution. 

Fixes #7907.

### CODE REVIEW

File: src/ol/control/ScaleLine.js [hunk 1]
```diff
@@ -179,7 +179,7 @@ ScaleLine.prototype.updateElement_ = function() {
     Units.METERS;
   let pointResolution =
       getPointResolution(projection, viewState.resolution, center, pointResolutionUnits);
-  if (projection.getUnits() != Units.DEGREES && units == ScaleLineUnits.METRIC) {
+  if (projection.getUnits() != Units.DEGREES) {
```
Comment (ahocevar) [inline src/ol/control/ScaleLine.js]: You'll probably need
```js
if (projection.getUnits() != Units.DEGREES && units != ScaleLineUnits.DEGREES) {
```

Comment (hyperknot) [reply src/ol/control/ScaleLine.js]: I think the `projection.getUnits()` 
part needs to be 
```
includes([Units.FEET, Units.METERS, Units.USFEET], projection.getUnits())
```

and `pointResolutionUnits == Units.METERS` or what you wrote (maybe this one is better documenting that we are converting from meters).

Comment (ahocevar) [reply src/ol/control/ScaleLine.js]: Please add a test case that shows what you're trying to achieve. It seems to me you're confusing projection units and scale line units. Also please reference the issue that this pull request is supposed to fix, for future reference.

**Comment by hyperknot** [comment]
OK, final solution:
1. Instead of hard-coded array, let's use `projection.getMetersPerUnit()` (!= undefined), as that's exactly the case when we can multiply by it.
2. Except for DEGREES, like it was originally.
3. Use `pointResolutionUnits == METERS` which is exactly the same condition as the one you suggested.

**Comment by hyperknot** [comment]
I'll add a test case, but need to familiarise myself with the code.

**Comment by hyperknot** [comment]
@ahocevar I've added the tests for all units, and also included an imperial unit test for the zoom levels loop (unrelated to this).
