### PR TITLE
Delete palette texture before creating a new context

### LINKED ISSUE #15786: WebGLTileLayer with palette style stops working after map.removeLayer/map.addLayer
**Describe the bug**
WebGLTileLayers with a style that includes a palette seem to break when removed and added back to map.

**To Reproduce**
1. Go to https://codesandbox.io/p/sandbox/cog-style-forked-2vg3p9?file=%2Findex.html%3A22%2C68 (A modified cog-style example w/ a button added to `addLayer()`/`removeLayer()` from map)
2. Click 'Add / Remove layer' button multiple times and see there is no problem.
3. Switch layer style to 'NDVI w/ palette 1'
4. Click 'Add / Remove layer' button multiple times and see there is now a black layer
5. Note in console warnings/errors (vary by browser) something along the lines of:
`WebGL warning: bindTexture: `tex` is from a different (or lost) WebGL context.` or `WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context`

**Expected behavior**
That the WebGLTileLayer shows with proper style when added back to map

### PR DESCRIPTION
**Pull request by tschaub**
When a WebGL layer is removed and the helper is disposed, we need to stop using any textures or other resources bound to the associated context.  This change makes it so palette textures used in rendering tiles are deleted from a context before that context is disposed.

I'll admit I'm not totally happy with the regression test.  Without the timeouts, removing and adding the layer does not trigger the error (in the main branch).  I tried adding `map.renderSync()` calls between, but couldn't get things to fail without waiting a while between the initial render and the remove/add.

Fixes #15786.

### CODE REVIEW

File: test/rendering/cases/cog-palette-add-remove/main.js [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+});
+
+// regression test for https://github.com/openlayers/openlayers/issues/15786
+setTimeout(() => {
+  map.removeLayer(layer);
+  map.addLayer(layer);
+  render({
+    message: 'palette still works after adding and removing layer',
+  });
+}, 500);
```
Comment (ahocevar) [inline test/rendering/cases/cog-palette-add-remove/main.js:49]: I was able to consistently see the problem with a `rendercomplete` listener instead of the `setTimout()`:
```suggestion
map.once('rendercomplete', () => {
  map.removeLayer(layer);
  map.addLayer(layer);
  render({
    message: 'palette still works after adding and removing layer',
  });
});
```

**Review by ahocevar — APPROVED** [review]
Thanks! You may want to consider my suggestion to use a `rendercomplete` listener instead of a `setTimeout`.
