### PR TITLE
Return loaded image when decode fails

### LINKED ISSUE #15097: ImageWMS source error after upgrading from v7.5.2 to v8.0.0
I have recently tried to upgrade OpenLayers from version 7.5.2 to 8.0.0.

I face an error when OpenLayers tries to load the images from the WMS source. The `load` function in `Image.js` catches an exception in line 190:

```
Image.js:190 DOMException: The source image cannot be decoded.
```

Strange thing is when I look at the request to my GeoServer, it comes back with `200 OK`, and I even see the PNG data in the response. Without changing anything else, and going back to v7.5.2, everything works fine. I also tried v8.1.0, the result is the same.

A have carefully studied the migration notes, and found nothing that could be related to this error.

### PR DESCRIPTION
**Pull request by ahocevar**
This pull returns a loaded image when decode() failed.

Fixes #15097

### CODE REVIEW

File: src/ol/Image.js [hunk 1]
```diff
@@ -317,7 +322,14 @@ export function decode(image, src) {
     image.src = src;
   }
   return image.src && IMAGE_DECODE && CREATE_IMAGE_BITMAP
-    ? image.decode().then(() => createImageBitmap(image))
+    ? image
+        .decode()
+        .then(() => createImageBitmap(image))
+        .catch((e) =>
+          image.complete && image.width
+            ? Promise.resolve(image)
```
Comment (tschaub) [inline src/ol/Image.js:330]:
```suggestion
            ? image
```

File: src/ol/Image.js [hunk 2]
```diff
@@ -317,7 +322,14 @@ export function decode(image, src) {
...
+            : Promise.reject(e)
```
Comment (tschaub) [inline src/ol/Image.js:331]:
```suggestion
            : throw e
```

**Review by tschaub — APPROVED** [review]

**Comment by mike-000** [comment]
Does the wrapping Promise in `decodeFallback` have any purpose?  Why not

    ? image
        .decode()
        .then(() => image)
        .catch((e) => {
          if (image.complete && image.width) {
            return image;
          }
          throw e;
        })
