### PR TITLE
Expire cache only when not loading tiles

### LINKED ISSUE #16364: OL 10.2.1: Getting error "ImageTile getImage() returns null" after which no new tiles are loaded
**Describe the bug**
Happens in OL v10.2.1 and does not happen in v9.2.4.

When moving and zooming the map I'm getting error message in browser console that ImageTile getImage() returns null. When getting the error, new tiles won't be loaded anymore. Happens at least with WMTS source, but can also be reproduced with OSM source. 

Frequency and effects of the issue seem to depend on the browser and layer source. With Chrome (v130.0.6723.117) and Safari (v18.0 (19619.1.26.111.10, 19619)) the issue happens every time in WMTS Tile Transitions example. With Firefox (v132.0.2) the issue is more difficult to reproduce.

Depending on map layer configuration and browser the effects can be:
- only error message in browser console
- new tiles won't be loaded
- map goes fully white and is unresponsive
  

**To Reproduce**
1. Go to WMTS Tile Transitions example: https://openlayers.org/en/latest/examples/wmts-dimensions.html
2. Move Sea-level slider value back and forth. 

ol-v10-issue-img1

After getting error in the console. Sea-level slider does nothing and map only displays tiles which have been loaded already.

ol-v10-issue-img2

Issue is also reproducible in example https://openlayers.org/en/latest/examples/full-screen-source.html when zooming the map in and out repeatedly in full screen mode.

### PR DESCRIPTION
**Pull request by ahocevar**
In the old canvas tile renderer, we only expired tiles that were not listed in `frameState.usedTiles`. Since we don't check that any more, we should only expire the cache when no tiles are loading, which is the case when the `renderComplete` flag is true. This avoids the case that loading tiles are expired, which is the reason for the problem reported in #16364.

Fixes #16364.

### CODE REVIEW

File: src/ol/renderer/canvas/TileLayer.js [hunk 1]
```diff
@@ -841,21 +843,25 @@ class CanvasTileLayerRenderer extends CanvasLayerRenderer {
...
+        const tileSourceKey = getUid(tileSource);
+        const wantedTiles = frameState.wantedTiles[tileSourceKey];
+        const tilesCount = wantedTiles ? Object.keys(wantedTiles).length : 0;
+        this.updateCacheSize(tilesCount);
+        this.tileCache_.expireCache();
+      };
+
+      frameState.postRenderFunctions.push(postRenderFunction);
+    } else {
+      frameState.animate = true;
```
Comment (ahocevar) [inline src/ol/renderer/canvas/TileLayer.js:863]: This fixes an issue with the new canvas tilelayer renderer. It can be seen in all our examples, e.g. https://openlayers.org/en/latest/examples/simple.html: Zoom in several times to a region with many labels on the map. Wait until the map is loaded. Then zoom out once using the '-' Button. You'll see that higher zoom tiles are rendered, which go away as soon as you start panning the map. The expected behavior would be to see the correct zoom tiles already after zooming out.

File: test/browser/spec/ol/renderer/canvas/Layer.test.js [hunk 2]
```diff
@@ -16,7 +16,7 @@ describe('ol/renderer/canvas/Layer', function () {
       layers: [
         new TileLayer({
           source: new XYZ({
-            url: 'spec/ol/data/osm/{z}-{x}-{y}.png',
+            url: 'spec/ol/data/osm-{z}-{x}-{y}.png',
```
Comment (ahocevar) [inline test/browser/spec/ol/renderer/canvas/Layer.test.js:19]: This is not strictly related, but I found the typo while investigating the tile layer renderer problem.

File: src/ol/renderer/canvas/TileLayer.js [hunk 3]
```diff
@@ -664,7 +665,12 @@ class CanvasTileLayerRenderer extends CanvasLayerRenderer {
           continue;
         }
       }
-      this.renderComplete = false;
+      if (tileState !== TileState.IDLE) {
+        allIdle = false;
+      }
+      if (tileState !== TileState.ERROR) {
+        this.renderComplete = false;
+      }
```
Comment (ahocevar) [inline src/ol/renderer/canvas/TileLayer.js:673]: When a tile has settled in the `ERROR` state, it also counts towards a completely rendered map, because it won't be re-fetched.

**Comment by ahocevar** [comment]
I did not mean to open a can of worms, but to get this right I had to fix another issue with the new canvas tile layer renderer.

File: src/ol/renderer/canvas/TileLayer.js [hunk 4]
```diff
@@ -841,21 +847,26 @@ class CanvasTileLayerRenderer extends CanvasLayerRenderer {
...
-      const tilesCount = wantedTiles ? Object.keys(wantedTiles).length : 0;
-      this.updateCacheSize(tilesCount);
-      this.tileCache_.expireCache();
-    };
-
-    frameState.postRenderFunctions.push(postRenderFunction);
+    if (this.renderComplete) {
+      /**
+       * Here we unconditionally expire the source cache since the renderer maintains
+       * its own cache.
```
Comment (tschaub) [inline src/ol/renderer/canvas/TileLayer.js:853]: Minor, but I think this comment is no longer correct (or related to what the code actually does).  [Initially](https://github.com/openlayers/openlayers/pull/15568/files#diff-ea22661e28efe5304b2c3a407112dccd7f89002aa2f784fac4fbae08aa75bffdR884-R893), we were managing the source cache here.

**Review by tschaub — APPROVED** [review]
