### PR TITLE
Set background fill style for each declutter label

### LINKED ISSUE #10949: backgroundFill color not respected when declutter is used
**Describe the bug**
All labels are displayed with the same backgroundFill color if declutter is specified.

**To Reproduce**
Without declutter even numbers have red backgroundFill, odd number blue
https://codesandbox.io/s/cluster-dq6it

If declutter is specified all numbers appear with the same color, either red or blue
https://codesandbox.io/s/cluster-cox1t

**Expected behavior**
The backgroundFill of the individual style should be used regardless of decluttering.

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #10949

fillStyle needs to be set for each label to handle declutter groups containing different styles

### CODE REVIEW

File: src/ol/render/canvas/Executor.js [hunk 1]
```diff
@@ -280,6 +280,7 @@ class Executor {
     context.lineTo.apply(context, p1);
     if (fillInstruction) {
       this.alignFill_ = /** @type {boolean} */ (fillInstruction[2]);
+      context.fillStyle = /** @type {import("../../colorlike.js").ColorLike} */ (fillInstruction[1]);
```
Comment (ahocevar) [inline src/ol/render/canvas/Executor.js:283]: Without a context.save/restore, doesn't this affect subsequent polygon fills?

Comment (mike-000) [reply src/ol/render/canvas/Executor.js:283]: It would if the the color isn't set each time, but `.fill_()` seems to rely on that as it is already doing save and restore for rotation https://github.com/openlayers/openlayers/blob/master/src/ol/render/canvas/Executor.js#L1038

Comment (ahocevar) [reply src/ol/render/canvas/Executor.js:283]: Well, since this seems to be an issue only when decluttering, I guess you are right. But then again, wouldn't it be anough to set the `fillStyle` here only when we're decluttering?
