### PR TITLE
Use data URI instead of whole empty image

### LINKED ISSUE #7090: ol.ImageTile doesn't load() properly after errors
We use a tile source that often fails, so our code includes a listener that calls load() on the tile to retry after an error.

We recently noticed that when we load a large map, if there are errors, then the same map image gets displayed in several places on the map. I think this is due to one of the recent changes in ol.ImageTile.

Here's what happens when a tile load error happens:
- ImageTime.handleImageError_() sets the image_ to point to a blank tile.
- Our code gets a callback telling us about the error, and we call load()
- The default loading function does "imageTile.getImage().src = src;"

This has just set a real source onto the 'blank' tile. Each time we get a load error we do the same thing, and all of the failing tiles end up sharing the same 'blank' image. I think a simple fix would be so set up a new image each time we attempt the load... but there may be something even easier.

### PR DESCRIPTION
**Pull request by ahocevar**
Replaces #7103.

Fixes #7090.

### CODE REVIEW

**Comment by ahocevar** [comment]
Accidentally committed more than I wanted. Will fix that.

File: src/ol/imagetile.js [hunk 1]
```diff
@@ -152,9 +152,9 @@ ol.ImageTile.prototype.unlistenImage_ = function() {
  * A blank image.
  * @type {HTMLCanvasElement}
```
Comment (fredj) [inline src/ol/imagetile.js]: should be `@type {string}`
