### PR TITLE
Consistent generics for vector(tile) layers, sources, formats

### LINKED ISSUE #15858: Can't run/compile angular/typescript application with OL > 9.0.0
**Describe the bug**
I've just upgraded to OL 9.2.3 from OL 8.1.0 and now OL can't compile due to what I think is internal import errors.
Previously I've been using OL together with package @types/ol for typedefinitions, but now it seems like OL has it's own.

After installing OL >9 i get errors like this  when trying to run/compile my application:

Multiple export errors like this for GeoJSON:
> Error: node_modules/ol/format/GeoJSON.d.ts:2:36 - error TS2307: Cannot find module 'geojson' or its corresponding type declarations.
> 2 export type GeoJSONObject = import("geojson").GeoJSON;

Errors like this:

> Error: node_modules/ol/layer/Heatmap.d.ts:89:99 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<FeatureLike> | VectorTile<FeatureLike>'.
>   Type 'VectorSource<FeatureType>' is not assignable to type 'VectorSource<FeatureLike>'.
>     Types of property 'setLoader' are incompatible.
>       Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<FeatureLike>) => void'.
>         Types of parameters 'loader' and 'loader' are incompatible.
>           Types of parameters 'arg4' and 'arg4' are incompatible.
>             Type '((arg0: FeatureType[]) => void) | undefined' is not assignable to type '((arg0: FeatureLike[]) => void) | undefined'.
>               Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: FeatureLike[]) => void'.
>                 Types of parameters 'arg0' and 'arg0' are incompatible.
>                   Type 'FeatureLike[]' is not assignable to type 'FeatureType[]'.
>                     Type 'FeatureLike' is not assignable to type 'FeatureType'.
>                       'FeatureLike' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'FeatureLike'.
>                         Type 'RenderFeature' is not assignable to type 'FeatureType'.
>                           'RenderFeature' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'FeatureLike'.
> 
> 89 declare class Heatmap<FeatureType extends import("../Feature.js").FeatureLike> extends BaseVector<import("../source/Vector.js").default<FeatureType>, WebGLPointsLayerRenderer> {

> Error: node_modules/ol/layer/VectorImage.d.ts:165:35 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<Feature<Geometry>>'.
>   Types of property 'setLoader' are incompatible.
>     Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<Feature<Geometry>>) => void'.
>       Types of parameters 'loader' and 'loader' are incompatible.
>         Types of parameters 'arg4' and 'arg4' are incompatible.
>           Type '((arg0: FeatureType[]) => void) | undefined' is not assignable to type '((arg0: Feature<Geometry>[]) => void) | undefined'.
>             Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: Feature<Geometry>[]) => void'.
>               Types of parameters 'arg0' and 'arg0' are incompatible.
>                 Type 'Feature<Geometry>[]' is not assignable to type 'FeatureType[]'.
>                   Type 'Feature<Geometry>' is not assignable to type 'FeatureType'.
>                     'Feature<Geometry>' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'Feature<Geometry>'.
> 
> 165     constructor(options?: Options<import("../source/Vector.js").default<FeatureType>> | undefined);

I'm maintaining a very large OpenLayers based application as well as a inner-source library based on OpenLayers, and I need som information that can point me in the right direction to fix this.

**To Reproduce**
Upgrade application from OL < 9 to OL > 9

**Expected behavior**
The application should compile/run

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #15858

In addition to fixing several type issues, this pull request sets defaults for all type parameters to layers, sources and formats - this way no generics need to be specified any more when the defaults are used.

### CODE REVIEW

**Comment by ahocevar** [comment]
Marked ready for review. I think this is as good as it gets. I experimented with extracting the FeatureType from the SourceType‘s FestureType type argument, but could not get it to work.

**Comment by RobertOrthofer** [comment]
This seems to have fixed the issues I had with `VectorLayers` and `VectorSources`.

**Comment by ahocevar** [comment]
Added a test to make sure we continue to pass `tsconfig`s with `skipLibCheck: false` in the future.

Thanks for any review.

File: src/ol/format/Feature.js [hunk 1]
```diff
@@ -113,7 +113,7 @@ import {
  * {@link module:ol/Feature~Feature} objects from a variety of commonly used geospatial
  * file formats.  See the documentation for each format for more details.
  *
- * @template {import('../Feature.js').FeatureClass} [T=typeof import('../Feature.js').default]
+ * @template {import('../Feature.js').FeatureClass} [FeatureClassType=import('./Feature.js').FeatureToFeatureClass<import("../Feature.js").default>]
```
Comment (tschaub) [inline src/ol/format/Feature.js:116]: Maybe you already tried this and it was a dead end, but it seems like it would be simpler if the template here were just this.

```
/**
 * @template {import('../Feature.js').default} T
 */
```

Or maybe it needs to be optional, not sure.

Then below, we could have this:
```js
    /**
     * @protected
     * @type {import('../Feature.js').FeatureClass}
     */
    this.featureClass = Feature;
```

I'm wondering if this would keep us from having to use `import('./Feature.js').FeatureToFeatureClass<import("../Feature.js").default>` in so many other places.

File: test/typescript/cases/cluster-source.ts [hunk 2]
```diff
@@ -5,7 +5,19 @@ import Point from '../../../src/ol/geom/Point.js';
...
+    source: new VectorSource({
+      features: [new Feature(new Point([0, 0]))],
+    }),
+  }),
+});
+
+export const layer2: VectorLayer<
+  Feature,
+  ClusterSource<Feature<Point>>
+> = new VectorLayer({
```
Comment (tschaub) [inline test/typescript/cases/cluster-source.ts:20]: I imagine TS people would expect to be able to use something like
```js
const layer: VectorLayer<ClusterSource<Feature<Point>>> = // ...
```

Meaning the `Feature` type parameter would not need to be repeated.

There is a [stack overflow post](https://stackoverflow.com/questions/49102449/nested-generics-in-function-definition-in-typescript) that makes it look like `infer` might be a way to have a single `@template` in the layer constructor representing the source type and to extract the named feature type.  I toyed around with this but could not get the right syntax (or make sense of the docs really).

I'm not sure if this is a limitation of the JSDoc support, but it seems like TypeScript would allow.

Comment (ahocevar) [reply test/typescript/cases/cluster-source.ts:20]: That's what I tried, but failed (see https://github.com/openlayers/openlayers/pull/15869#issuecomment-2132397184)

File: src/ol/format/Feature.js (hunk 1 above)
Comment (ahocevar) [reply src/ol/format/Feature.js:116]: If we did that, we'd lose the ability to infer the return type of `readFeatures()` etc. to infer the feature type from the configured `featureClass`.
