### PR TITLE
Compare matrix transforms with lower precision

### LINKED ISSUE #16742: Multiple canvases with the same class name for layers when browser zoom level is set to 90%/75%
**Describe the bug**
When using a 90% zoom level in browsers (Edge or Chrome), the composite transform calculated for the canvas element is `matrix(1.111111, 0, 0, 1.111111, 0, 0)`. However, when this transform is applied to the HTML canvas styles, the values are rounded to `matrix(1.11111, 0, 0, 1.11111, 0, 0)` (with an extra decimal place dropped).

As a result, the container of the previous layer renderer will not be reused because the logic performs a strict comparison to check if the transform values are identical. It then creates a new canvas element for each layers.

The same issue occurs when the zoom level is set to 75%.

**To Reproduce**
1. Set the browser zoom level to 90%
2. Load the example page https://openlayers.org/en/latest/examples/canvas-tiles.html
3. Inspect the map element in the browser's developer tools.
4. Observe that there are two `<div>` elements with the class `ol-layer`, each containing a <canvas> element under `ol-viewport`.

**Expected behavior**
Only one `<div>` element with the class `ol-layer` should be created, similar to how the map behaves at other zoom levels, without the unnecessary creation of duplicate canvas elements.

### PR DESCRIPTION
**Pull request by ahocevar**
Alternative to #16743.
Fixes #16742.

### CODE REVIEW

**Review by tschaub — APPROVED** [review]

File: src/ol/transform.js [hunk 1]
```diff
@@ -267,23 +267,45 @@ export function determinant(mat) {
...
+ * @param {!string} cssTransform2 A CSS transform matrix string.
+ * @return {boolean} The two matrices are equal.
+ */
+export function equivalent(cssTransform1, cssTransform2) {
+  const mat1 = fromString(cssTransform1);
+  const mat2 = fromString(cssTransform2);
+  for (let i = 0; i < 6; ++i) {
+    if (
+      Math.round(mat1[i] * matrixPrecision[i]) / matrixPrecision[i] !==
+      Math.round(mat2[i] * matrixPrecision[i]) / matrixPrecision[i]
```
Comment (M393) [inline src/ol/transform.js:305]:
```suggestion
      Math.round(mat1[i] * matrixPrecision[i]) !== Math.round(mat2[i] * matrixPrecision[i])
```
