### PR TITLE
Clamp EPSG:3857 y to lowest/highest possible value instead of validity extent

### LINKED ISSUE #11672: Rendering of reprojected VectorImage layers seems broken from v6.3.1 -> v6.4.3
**Describe the bug**
Rendering of Vector sources on a VectorImage layer seems to be broken in v6.4.3, when the vector source has EPSG:4326 projection covering the whole globe, and the map is in EPSG:3857. It seems that the reprojection goes wrong, as EPSG:4326 exceeds the extent of EPSG:3857 (at high latitudes). It results in several layers of false polygons that are drawn on top of the correct ones, sometimes covering the whole map.

**To Reproduce**
1.) create a Vector source from a GeoJSON file containing polygons in EPSG:4326 covering the whole world (-180 to 180W and -90 to 90N).
2.) create a VectorImage layer with the Vector source
3.) add that layer to a map that is created with a view with projection EPSG:3857
4.) zoom and pan around and see flickering false polygons covering the map

**Expected behavior**
Not seeing any false polygons, like it is the case if you did add the same layer to a map with a view in EPSG:4326 (not reprojecting the source).

### PR DESCRIPTION
**Pull request by ahocevar**
Although the validity extent of EPSG:3857 in y direction only ranges from ~-85 to ~85 degrees, lower/higher values can be handled. To avoid geometries getting corrupted topologically when transforming values from high/low latitudes, we can clamp to the lowest/highest safe value instead of the validity extent.

Improves (but does not fix) #11672.

### CODE REVIEW

File: src/ol/proj/epsg3857.js [hunk 1]
```diff
@@ -31,6 +31,13 @@ export const EXTENT = [-HALF_SIZE, -HALF_SIZE, HALF_SIZE, HALF_SIZE];
  */
 export const WORLD_EXTENT = [-180, -85, 180, 85];
 
+/**
+ * Maximum safe value in y direction
+ * @const
+ * @type {number}
+ */
+export const MAX_SAFE_Y = RADIUS * Math.log(Math.tan((Math.PI * 180) / 360));
```
Comment (MoonE) [inline src/ol/proj/epsg3857.js:39]: This looks a bit weird calculating with radians.
```suggestion
export const MAX_SAFE_Y = RADIUS * Math.log(Math.tan(Math.PI / 2));
```

**Review by tschaub — APPROVED** [review]
