### PR TITLE
Fixes failing tests for Chrome v74

### LINKED ISSUE #9288: Failing test (ol.control.ScaleLine)
**Tests - Failing**

Currently the `ol.control.ScaleLine` test is failing under the following requirements:
- Linux Mint 19.1 Tessa (Ubuntu 18.04)
- Node 8.11.3 or 10.15.0

```
Chrome 74.0.3723 (Linux 0.0.0) ol.control.ScaleLine projections affect the scaleline Projection's metersPerUnit affect scale for non-degree units FAILED
	Error: expected '0.000049999999999999996 nm' to equal '0.00005 nm'

```

IMHO it is a Bug in the Chrome-Version (74.0.3723) which gets [launched via puppeteer](https://github.com/openlayers/openlayers/blob/master/test/karma.config.js#L77).

Math.pow seems to be broken:

```js
// Chrome-Version (71.0.3578.98)
console.log(Math.pow(10, -5)); // 0.00001

// Chrome-Version (74.0.3723)
console.log(Math.pow(10, -5)); // 0.000009999999999999999
```

**To Reproduce**
1. Fresh checkout
2. `npm i`
3. `npm run test` or `npm run karma`

**Possible Solution**
The [current karma config](https://github.com/openlayers/openlayers/blob/master/test/karma.config.js#L77) uses the chrome binary which gets installed via puppeteer. This seems to be the canary/dev build and not the stable chrome version. I think it would be better to use the stable chrome version for the tests.
Of course this is not a bug within OpenLayers but it leads to failing tests which might be avoided.

**Expected behavior**
No test should fail.

### PR DESCRIPTION
**Pull request by KaiVolland**
This fixes failing test (ol.control.ScaleLine) which failed in Chrome v74. See #9288.

The previous solution (#9292) is reverted by updating the puppeteer to `~1.13.0`. 
The new solution is to compensate the inaccurate calculation by using `toFixed()` [as proposed](https://github.com/openlayers/openlayers/pull/9292#issuecomment-470460362).

Fixes #9288

### CODE REVIEW

**Comment by KaiVolland** [comment]
Ouch. Seems like i some rendering tests need to be fixed, too.

File: src/ol/control/ScaleLine.js [hunk 1]
```diff
@@ -262,8 +262,10 @@ class ScaleLine extends Control {
       Math.log(this.minWidth_ * pointResolution) / Math.log(10));
     let count, width;
     while (true) {
-      count = LEADING_DIGITS[((i % 3) + 3) % 3] *
-          Math.pow(10, Math.floor(i / 3));
+      const decimalCount = Math.floor(i / 3);
+      const decimal = Number(Math.pow(10, decimalCount)
+        .toFixed(Math.abs(decimalCount)));
+      count = LEADING_DIGITS[((i % 3) + 3) % 3] * decimal;
```
Comment (ahocevar) [inline src/ol/control/ScaleLine.js]: It's better to apply `toFixed()` to the number when it gets finally rendered, instead of converting it to string and back to number, and then continue doing calculations with it.

Comment (KaiVolland) [reply src/ol/control/ScaleLine.js]: As the error/inaccuracy occurs right in `Math.pow`, wouldn't it be better to correct it right afterwards before continuing to calculate with the wrong value?

Comment (ahocevar) [reply src/ol/control/ScaleLine.js]: No, because we might be running into other floating point issues further down the line. Since we calculate this only for displaying the scale, it's best to do the formatting when displaying the scale.

Comment (KaiVolland) [reply src/ol/control/ScaleLine.js]: Ok.

Comment (KaiVolland) [reply src/ol/control/ScaleLine.js]: Resolve due to force push.

File: src/ol/control/ScaleLine.js [hunk 2]
```diff
@@ -274,11 +275,13 @@ class ScaleLine extends Control {
       }
       ++i;
     }
-
     let html;
     if (this.scaleBar_) {
       html = this.createScaleBar(width, count, suffix);
     } else {
+      if (count % 1 !== 0) {
```
Comment (ahocevar) [inline src/ol/control/ScaleLine.js]: You could play this save and replace the if-block with something that also works for numbers where you don't want decimal places:
```js
html = count.toFixed(decimalCount < 1 ? -decimalCount : 0) + ' ' + suffix;
```
