### PR TITLE
Clear layer tile cache when view projection reset

### LINKED ISSUE #16136: Map not update when reprojected.
**Description**
When setting a new projection from the code, the map is not updated for the new projection.

**To Reproduce**
1. Go to [this ol example](https://openlayers.org/en/latest/examples/reprojection-by-code.html)
2. Select a new projection ex: EPSG:32661 (UPS North).
3. The map is well updated.
4. Select another projection ex: EPSG:32761 (UPS South).
5. The map is not updated. To update it correctly we need to make an explicit action triggering the refresh of it, like "Render reprojection edges" for exemple.

**Expected behavior**
In the previous versions, on change of the projection in the view, or set of a new view with different projection, the map was updated for the new projection without the need to force its refresh.

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #16136

### CODE REVIEW

File: src/ol/renderer/canvas/TileLayer.js [hunk 1]
```diff
@@ -206,6 +206,12 @@ class CanvasTileLayerRenderer extends CanvasLayerRenderer {
      */
     this.tileCache_ = new LRUCache(cacheSize);
 
+    /**
+     * @private
+     * @type {import("../../proj/Projection.js").default}
+     */
+    this.projection_ = undefined;
```
Comment (ahocevar) [inline src/ol/renderer/canvas/TileLayer.js:213]: Maybe rename this to `renderedProjection_`?

**Review by ahocevar — CHANGES_REQUESTED** [review]
Thanks, @mike-000. I have one minor suggestion.

**Review by ahocevar — APPROVED** [review]

**Comment by ahocevar** [comment]
Thanks, @mike-000
