### PR TITLE
Vector source / prevent adding features with duplicate id in the collection

### LINKED ISSUE #6183: ol.source.Vector with spatial index and ol.Collection for features is broken
I got a simple map that request geojson features dynamically based on extent of the map from a WFS (geoserver). 

For some reason, I need to only load the features on the extent. So after map pan (map.on('moveend')) I clear a ol.Collection and repopulate the Collection with the new requested features. 

The problem happen on the first clear (move the map). I get the error message:

    Cannot read property 'forEach' of undefined

The error seams to come from the event propagation of the pop event and append in the function

    ol.source.Vector.prototype.removeFeatureInternal

Here is a sample code and the jsbin of the reproductible error

```javascript
var myCollection = new ol.Collection();

var myLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
        features: myCollection
    })
})

function myUpdateFunction() {
    // var url = 'https://raw.githubusercontent.com/johan/world.geo.json/master/countries/USA/WY.geo.json'
    var url = "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json";
    $.get(url).then(function(result) {
        var format = new ol.format.GeoJSON({
            defaultDataProjection: "EPSG:4326",
            featureProjection: "EPSG:3857"
        });
        var features = format.readFeatures(result);

        myCollection.clear();
        myCollection.extend(features);
    });
}

var map = new ol.Map({
    layers: [
        new ol.layer.Tile({source: new ol.source.OSM()}),
        myLayer
    ],
    target: 'map',
    controls: ol.control.defaults({
        attributionOptions:({collapsible: false})
    }),
    view: new ol.View({center: [0, 0],zoom: 2})
});

map.on('moveend', function(e) {
    myUpdateFunction();
});

```
https://jsbin.com/tivezamufi/1/edit?html,js,console,output

### PR DESCRIPTION
**Pull request by jahow**
Previously two features with the same id could be pushed manually in the features collection and stay there.

This would cause an error when clearing the source (related to change events not registered for the features with duplicate id).

This only happened when manipulating the source directly (either through `extend()` or `push()`).

Fixes #6183.

Note: the added test fails without the change in the source code.

### CODE REVIEW

**Comment by jahow** [comment]
This fix is more of a workaround really, as we can't prevent adding features with the same id directly in the collection. I've tested it with the code provided in the original issue and it works well.

Thanks for any review

File: src/ol/source/Vector.js [hunk 1]
```diff
@@ -299,12 +299,12 @@ class VectorSource extends Source {
   addFeatureInternal(feature) {
     const featureKey = getUid(feature);
 
+    this.setupChangeEvents_(featureKey, feature);
```
Comment (ahocevar) [inline src/ol/source/Vector.js]: This change will leave change events registered on features that could not be added to the source (i.e. with a spatial index).

File: src/ol/source/Vector.js [hunk 2]
```diff
@@ -299,12 +299,12 @@ class VectorSource extends Source {
...
+
     if (!this.addToIndex_(featureKey, feature)) {
       return;
```
Comment (ahocevar) [inline src/ol/source/Vector.js]: It would be better to remove the feature from the collection here, if there is a collection.

Comment (jahow) [reply src/ol/source/Vector.js]: Problem is, `addFeatureInternal` can be called from a collection `add` event, so it would mean removing an element while adding it... would that be possible?

See: https://github.com/openlayers/openlayers/blob/ddb7da37336f803c635d3becfd316047615944a6/src/ol/source/Vector.js#L451

Comment (ahocevar) [reply src/ol/source/Vector.js]: That should work.

**Comment by jahow** [comment]
I've updated the PR following @ahocevar's suggestion, and it looks better indeed. Thanks
