### PR TITLE
Remove `layerState` param from `prepareFrame` and `renderFrame` function

### LINKED ISSUE #9587: setOpacity doesn't work on ol/layer/Group
**Describe the bug**
I have a couple layers displayed on my map, most react well to `setOpacity` and I have a reluctant one that doesn't change its transparency when `setOpacity` is applied

**To Reproduce**
https://s.geo.admin.ch/820917c58e and try to change opacity on both visible layers, the one with buildings and dwellings doesn't work when the other does (same code and same layer type `ol/layer/Tile`)

That's something new with OL6 betas as it's working fine on 5.3 (see https://s.geo.admin.ch/82092c7fd6)
I don't really know where to look for clues, we are using `setOpacity()` to set this property in our code.
layer creation here https://github.com/geoadmin/mf-geoadmin3/blob/845b8d131b909fa34116504c9cfcf2387303724b/src/components/map/LayersService.js#L540-L549
opacity set here https://github.com/geoadmin/mf-geoadmin3/blob/845b8d131b909fa34116504c9cfcf2387303724b/src/components/map/DefinePropertiesForLayerService.js#L50-L57

**Expected behavior**
Same behaviour when changing opacity.

### PR DESCRIPTION
**Pull request by fredj**
replaces #9591

Instead of passing the `layerState` to the `prepareFrame` and `renderFrame` functions, the state is now taken from the `frameState` by using the new `layerIndex` property:
```
frameState.layerStatesArray[frameState.layerIndex];
```

fixes #9587

### CODE REVIEW

File: src/ol/layer/Base.js [hunk 1]
```diff
@@ -83,6 +83,9 @@ class BaseLayer extends BaseObject {
   }
 
   /**
+   * This method is not meant to be called by layers or layer renderers because the state
+   * is iccorect if the layer is included in a layer group.
```
Comment (tschaub) [inline src/ol/layer/Base.js]:
```suggestion
   * is incorrect if the layer is included in a layer group.
```

**Comment by fredj** [comment]
Thanks for the review
