### PR TITLE
Promise based vector loader; fix failure handling

### LINKED ISSUE #17335: VectorSource remains loading after loader failure
**Describe the bug**
When an `VectorSource` uses a custom async `loader` that ends in `failure()` (e.g. service unreachable) and no features are ever added, the map can emit `loadstart` but never `loadend`.

OpenLayers version: 10.8.0 (npm `ol`).

Workaround: calling `source.changed()` after invoking `failure()` seems to clear the stuck loading state.

**To Reproduce**
1. Clone https://github.com/anticultist/ol-vector-source-issue
2. Run `npm install`
3. Run `npm run start`
4. Open the printed local URL in a browser
5. On load, the `VectorSource` loader schedules `failure()` (via `setTimeout(...)`), never calls `success(...)`, and never adds features
6. Observe that the map fires `loadstart` and the status panel shows `loading: true`
7. Observe that the map never fires `loadend` and the status panel never returns to `loading: false`

**Expected behavior**
After the loader reports failure and there are no pending loads, the source should leave the loading state, allowing the map to emit `loadend`.

### PR DESCRIPTION
**Pull request by ahocevar**
The motivation for this pull request was to fix #17335. But while digging into the problem and the discussion in #17395, I figured when touching the way custom loaders work, it would be good to modernize the API and make it promise based. The old flavor still works, because it's also used by the internal xhr loader.

Here is the result. The key benefit is that it is no longer necessary to both add the features to the source and call the success callback with the features as argument. The modified exmaple shows the simplification.

The fix for #17335 is that in the internal failure callback, `source.changed()` needs to be called - this effectively also happens when the loaded features are added to the source upon success.

I decided to remove the `loadedExtentCount_` member variable, because it needed to be kept in sync with `loaded`. Instead, `loaded` can now be a `number` or a `boolean`. No need to make any other changes related to that, because it is only checked for a truthy value in Map.js.

### CODE REVIEW

File: src/ol/featureloader.js
Comment (jahow) [inline src/ol/featureloader.js]: Sorry I also missed that this bit of documentation should also mention the possibility to return a promise.

File: src/ol/featureloader.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ let withCredentials = false;
  *           resolution: number,
  *           projection: import("./proj/Projection.js").default,
  *           success?: (features: Array<FeatureType>) => void,
- *           failure?: () => void) => void} FeatureLoader
+ *           failure?: () => void) => void|Promise<Array<FeatureType>>} FeatureLoader
```
Comment (jahow) [inline src/ol/featureloader.js:34]: Last thing but not related to the PR, this typedef (as well as the one from `FeatureUrlFunction` do not render in the docs at all.

Image

If you're up for some boyscoutting

Comment (ahocevar) [reply src/ol/featureloader.js:34]: That's a big issue unfortunately, something for a future effort (beyond boyscouting).

**Comment by ahocevar** [comment]
Thanks for the thorough review, @jahow. I'm going to add another commit with the doc improvements you suggested, and I'll do both - mark the old flavor as deprecated, and make sure that success/failure is not called manually when a promise is used.
