### PR TITLE
Calculate reprojection tile ranges for each world

### LINKED ISSUE #15804: Missing tiles in WebGLTileLayer with a GeoTiff source
**Describe the bug**
After reprojecting GeoTiff tiles into a stereographic projection, tiles near the antimeridian are not rendered. 
The sizes of the resulting black gaps (please see the picture below) depend on the sizes of source tiles and zoom.

image

**To Reproduce**
1. Download the geotiff sample image (zipped): 
[202404152030.zip](https://github.com/openlayers/openlayers/files/15231597/202404152030.zip)

2. Initialize WebGLTileLayer:
```
new WebGLTileLayer({
     source: new GeoTIFF({sources: [{url: url}], crossOrigin: 'anonymous', transition: 0, normalize: true}),
     name: 'segments',
     zIndex: 2,
     cacheSize: 2048,
     preload: 0,
     isActive: true
})
```
3. Register a stereographic projection
```
proj4.defs('stereo-sib', '+proj=stere +lat_0=49 +lat_ts=-73 +lon_0=90 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');
register(proj4);
```
4. Initialize View
```
const view = new View({
  projection: getProjection('stereo-sib'),
  center: fromLonLat([-175.63918171041328, 54.36175564445709], defaultProj),
  zoom: 5.370370380181835,
  minZoom: 4
});
```
5. Observe.

**Expected behavior**
There should be no missing tiles aroung the antimeridian.

### LINKED ISSUE #15824: Reprojection issues with `wrapX: false`
**Describe the bug**
Raising a new issue because the problem described in #15804 is not confined to DataTile sources.

When a source is reprojected the `wrapX` setting should determine whether the ReprojTiles wrap in the destination projection, while the source tiles are taken from the real world.  In non-parallel projections this does not always happen, tiles with x coordinate -1 are considered invalid if `wrapX` is false.

**To Reproduce**
This is a particular issue for DataTile sources where `wrapX` has a different meaning (see #15804) but the problem can also be reproduced in canvas layers as in https://jsfiddle.net/0ncuwr2L/ where the OSM source has `wrapX: false` and the custom debug source with `wrapX: true` shows tile coordinates with negative x values where OSM tiles are not rendered (note the standard TileDebug source would show XYZ values used in a tile url).  A workaround such as setting the source projection non-global or simulating that as in #15815 does not work as expected and produces artefacts even in canvas layers.

**Expected behavior**
Reprojection should not rely on, for example, coordinate `[3, -1, 1]` being loaded with the same url as `[3, 7, 1]` but instead use the real world tile `[3, 7, 1]` appropriately offset in the stitch context regardless of the `wrapX` setting.  Any tiles which overflow a world extent (or for DataTile sorces the tile grid extent) should be clipped when drawn to the stitch context.

In most cases this would work by replacing

          const tile = getTileFunction(this.sourceZ_, srcX, srcY, pixelRatio);
          if (tile) {
            this.sourceTiles_.push(tile);
          }

and

    this.sourceTiles_.forEach((tile) => {
      if (tile && tile.getState() == TileState.LOADED) {
        sources.push({
          extent: this.sourceTileGrid_.getTileCoordExtent(tile.tileCoord),
          image: tile.getImage(),
        });
      }
    });

in the ReprojTile source with

          let tileCoord = [this.sourceZ_, srcX, srcY];
          const extent = sourceTileGrid.getTileCoordExtent(tileCoord)
          if (sourceProj.canWrapX()) {
            tileCoord = wrapX(sourceTileGrid, tileCoord, sourceProj);
          }
          const tile = getTileFunction(...tileCoord, pixelRatio);
          if (tile) {
            this.sourceTiles_.push({tile, extent});
          }

and

    this.sourceTiles_.forEach((source) => {
      const tile = source.tile;
      if (tile && tile.getState() == TileState.LOADED) {
        sources.push({
          extent: source.extent,
          image: tile.getImage(),
        });
      }
    });

However using `ol/tilegrid#wrapX` does not work well with tile grids such as that in #15804 which where tiles overflow the projection extent.  Splitting the source extent into separate worlds and calculating ranges for each would fix that. for example

      let worldWidth = 0;
      let worldsAway = 0;
      if (sourceProj.canWrapX()) {
        worldWidth = getWidth(sourceProjExtent);
        worldsAway = Math.floor(
          (sourceExtent[0] - sourceProjExtent[0]) / worldWidth,
        );
      }

      const sourceExtents = wrapAndSliceX(sourceExtent.slice(), sourceProj);
      sourceExtents.forEach((extent) => {
        const sourceRange = sourceTileGrid.getTileRangeForExtentAndZ(
          extent,
          this.sourceZ_,
        );

        for (let srcX = sourceRange.minX; srcX <= sourceRange.maxX; srcX++) {
          for (let srcY = sourceRange.minY; srcY <= sourceRange.maxY; srcY++) {
            const tile = getTileFunction(this.sourceZ_, srcX, srcY, pixelRatio);
            if (tile) {
              const offset = worldsAway * worldWidth;
              this.sourceTiles_.push({tile, offset});
            }
          }
        }
        ++worldsAway;
      });

and

    this.sourceTiles_.forEach((source) => {
      const tile = source.tile;
      if (tile && tile.getState() == TileState.LOADED) {
        const extent = this.sourceTileGrid_.getTileCoordExtent(tile.tileCoord);
        extent[0] += source.offset;
        extent[2] += source.offset;
        sources.push({
          extent: extent,
          image: tile.getImage(),
        });
      }
    });

Tile `[3, 19, 1]` is then correctly positioned next to `[3, 0, 1]`, but in the final fix it should be clipped at the projection edge instead of overlapping
image

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #15824
Fixes #15804

Added rendering tests for ImageTile  based on failing example in #15824 and for DataTile based on tile grid used in #15804,

### CODE REVIEW

File: src/ol/reproj/DataTile.js [hunk 1]
```diff
@@ -444,7 +491,8 @@ class ReprojDataTile extends DataTile {
     let leftToLoad = 0;
 
     this.sourcesListenerKeys_ = [];
-    this.sourceTiles_.forEach((tile) => {
+    this.sourceTiles_.forEach((source) => {
+      const tile = source.tile;
```
Comment (ahocevar) [inline src/ol/reproj/DataTile.js:495]:
```suggestion
    this.sourceTiles_.forEach(({tile}) => {
```

File: src/ol/reproj/DataTile.js [hunk 2]
```diff
@@ -477,7 +525,8 @@ class ReprojDataTile extends DataTile {
     if (leftToLoad === 0) {
       setTimeout(this.reproject_.bind(this), 0);
     } else {
-      this.sourceTiles_.forEach(function (tile) {
+      this.sourceTiles_.forEach(function (source) {
+        const tile = source.tile;
```
Comment (ahocevar) [inline src/ol/reproj/DataTile.js:529]:
```suggestion
      this.sourceTiles_.forEach(function ({tile}) {
```

File: src/ol/reproj/Tile.js [hunk 3]
```diff
@@ -298,7 +340,8 @@ class ReprojTile extends Tile {
       let leftToLoad = 0;
 
       this.sourcesListenerKeys_ = [];
-      this.sourceTiles_.forEach((tile) => {
+      this.sourceTiles_.forEach((source) => {
+        const tile = source.tile;
```
Comment (ahocevar) [inline src/ol/reproj/Tile.js:344]:
```suggestion
      this.sourceTiles_.forEach(({tile}) => {
```

File: src/ol/reproj/Tile.js [hunk 4]
```diff
@@ -330,7 +373,8 @@ class ReprojTile extends Tile {
       if (leftToLoad === 0) {
         setTimeout(this.reproject_.bind(this), 0);
       } else {
-        this.sourceTiles_.forEach(function (tile, i, arr) {
+        this.sourceTiles_.forEach(function (source, i, arr) {
+          const tile = source.tile;
```
Comment (ahocevar) [inline src/ol/reproj/Tile.js:377]:
```suggestion
        this.sourceTiles_.forEach(function ({tile}, i, arr) {
```

**Review by ahocevar — CHANGES_REQUESTED** [review]
Thanks, @mike-000. The code looks good, I only added a few syntactic simplification suggestions.
