### PR TITLE
Check if the sketch feature is defined in finishDrawing

### LINKED ISSUE #7035: Function FinishDrawing cause error if zero point in geometry
https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/draw.js#L640

Calling ol.interaction.Draw.FinishDrawing doesn't check if there is a geometry and cause a javascript error.

Step to reproduce:

start an ol.interaction.draw
call finishDrawing() before adding any point
it cause an error

### PR DESCRIPTION
**Pull request by fredj**
Fixes #7035

### CODE REVIEW

File: src/ol/interaction/Draw.js [hunk 1]
```diff
@@ -714,37 +714,39 @@ Draw.prototype.removeLastPoint = function() {
...
-    // remove the redundant last point
-    coordinates.pop();
-    this.geometryFunction_(coordinates, geometry);
-  } else if (this.mode_ === Draw.Mode_.POLYGON) {
-    // remove the redundant last point in ring
-    coordinates[0].pop();
-    this.geometryFunction_(coordinates, geometry);
-    coordinates = geometry.getCoordinates();
-  }
+  if (sketchFeature) {
```
Comment (tschaub) [inline src/ol/interaction/Draw.js]: Might be more readable & less prone to future error to shorten this block.  E.g.
```js
if (!sketchFeature) {
  return;
}
// ...
```

Comment (fredj) [reply src/ol/interaction/Draw.js]: yes, changed
