### PR TITLE
Fix offscreen-canvas example

### LINKED ISSUE #16140: Offscreen canvas example not working
**Describe the bug**
The Offscreen canvas example was working in version 9.2.4, but is not in 10.0.0 or 10.1.0

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #16140

### CODE REVIEW

File: src/ol/style/IconImage.js [hunk 1]
```diff
@@ -251,11 +251,14 @@ class IconImage extends EventTarget {
     }
 
     const image = this.image_;
-    const canvas = document.createElement('canvas');
+    const ctx = createCanvasContext2D(
+      Math.ceil(image.width * pixelRatio),
+      Math.ceil(image.height * pixelRatio),
+    );
+    const canvas = ctx.canvas;
     canvas.width = Math.ceil(image.width * pixelRatio);
```
Comment (mike-000) [inline src/ol/style/IconImage.js:259]: width and height only needs to be set once

**Review by tschaub — APPROVED** [review]
