### PR TITLE
Handle Graticule wrapX without calculating excess meridians

### LINKED ISSUE #10799: Missing meridians in zoomed in wrapped graticule
**Describe the bug**
I noticed the problem while testing #10795 but it does not appear to be related to that or other recent changes and can also be seen in version 6.2.1.

**To Reproduce**
Open the example https://openlayers.org/en/latest/examples/graticule.html in code sandbox and comment out both `wrapX: false` lines.  Pan from the "normal" world to an adjacent world and zoom in.  Instead of the interval continuing to reduce similar to the parallels the meridians disappear below an interval of 1 degree.  In the "normal" world the meridians do not disappear.

**Expected behavior**
Meridians should appear at all intervals in all worlds.

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #10799

When wrapped the renderer was calling the loader function with the full width of the projection resulting in the graticule attempting to calculate meridians for the whole world even when zoomed in on a small region.  This exceeded the `maxLines` limit and resulted in missing meridians, unnecessarily long parallels and poor performance.  It is fixed by the vector layer renderer always calling the loader with the frameState extent for Graticule layers and handling wrapping in the graticule.

### CODE REVIEW

**Comment by ahocevar** [comment]
The changes to the renderer are problematic. If the Graticule layer handles wrapX, wouldn't it be enough to configure its source always with `wrapX: false`?

**Comment by mike-000** [comment]
The graticule only handles wrapX in as much as it moves the provided extent to a normal world (possibly overlapping another world) to avoid unnecessary loader processing.  The renderer's replay groups and renderFrame are not affected and will need a wrapX source to render that onto other worlds.

**Comment by ahocevar** [comment]
I see @mike-000. In this case, it would make sense to move the +/-540° logic from the renderer to `ol/source/Vector`'s `loadFeatures()` method, so it would not affect the Graticule if it uses a customized vector source.

**Comment by mike-000** [comment]
Even custom loaders are called from `loadFeatures` so that would be a breaking change for anything which used a custom loader.  Maybe instead of hardcoding a test for a specific layer type a new source property is needed to indicate which extent is passed to loaders when wrapped.  It might also be useful for loading WFS features in small areas such as Fiji which would otherwise request data from across the world.

**Comment by ahocevar** [comment]
@mike-000 That sounds good. What about a `getLoadExtent()` method on the source?

**Comment by ahocevar** [comment]
@mike-000 Thanks for your continued effort on this. I'm inclined to always pass an extent with a real world center to the loader, regardless of whether the source is a graticule or a plain vector layer. If you agree, I'll add a commit to your branch to show you what I mean.

**Comment by mike-000** [comment]
Yes, the loader having the majority of the extent in a real world makes sense even if it wraps onto another, and if entirely in one world it wouldn't need to be concerned about which one.

**Comment by ahocevar** [comment]
@mike-000 Ok, committed.

One thing I noticed (but that might be an issue beyond the scope of this pull request) is that when `wrapX` is set to true in the `graticule.html` example, no meridian labels will be shown outside the real world.

**Comment by mike-000** [comment]
That is because this PR was started before #10795 was merged.  These changes are not related and should be no conflict with that.

**Comment by mike-000** [comment]
I suspect the removal of `loadWrapX` is going to be a breaking change. In this case always basing the load extent on the frameStateExtent would result in an approximate request for either -184 to -176 or +176 to +184 (depending on the exact position of the center).  Will all data sources return results from both sides of the dateline for such requests?  If not the `loadWrapX` is still needed to get all results from -180 to +180 (which might results in a lot of excess data from a global source) or the loader would need to make two requests, one on each side of the dateline.
image

**Comment by ahocevar** [comment]
That's a valid concern @mike-000. I added another commit so now two extents are loaded in these cases. You may want to take another final look at your changes to make sure everything still works.

File: src/ol/layer/Graticule.js [hunk 1]
```diff
@@ -479,11 +479,25 @@ class Graticule extends VectorLayer {
...
+    if (this.projection_) {
+      const center = getCenter(extent);
+      const projectionExtent = this.projection_.getExtent();
+      const worldWidth = getWidth(projectionExtent);
+      if (this.getSource().getWrapX() && this.projection_.canWrapX() && !containsExtent(projectionExtent, extent)) {
+        const worldsAway = Math.floor((center[0] - projectionExtent[0]) / worldWidth);
+        realExtent[0] -= (worldsAway * worldWidth);
+        realExtent[2] -= (worldsAway * worldWidth);
+      }
+      realExtent[0] = Math.round(realExtent[0] * 1e6) / 1e6;
```
Comment (ahocevar) [inline src/ol/layer/Graticule.js]: Better use the resolution to round to pixels, instead of hard-coding `1e6`.

File: src/ol/layer/Graticule.js [hunk 2]
```diff
@@ -479,11 +479,25 @@ class Graticule extends VectorLayer {
...
-    if (this.loadedExtent_ && !equals(this.loadedExtent_, extent)) {
+    // extents may be passed in different worlds, to avoid endless loop we use only one
+    const realExtent = extent.slice();
+    if (this.projection_) {
+      const center = getCenter(extent);
+      const projectionExtent = this.projection_.getExtent();
+      const worldWidth = getWidth(projectionExtent);
+      if (this.getSource().getWrapX() && this.projection_.canWrapX() && !containsExtent(projectionExtent, extent)) {
+        const worldsAway = Math.floor((center[0] - projectionExtent[0]) / worldWidth);
+        realExtent[0] -= (worldsAway * worldWidth);
```
Comment (ahocevar) [inline src/ol/layer/Graticule.js]: We're doing this same operation a lot. I think a `toRealWorld(extent, projection)` function in `ol/extent` could be nice.

File: src/ol/layer/Graticule.js (hunk 1 above)
Comment (mike-000) [reply src/ol/layer/Graticule.js]: I don't think it is related to resolution. There is a javascript rounding problem when adding or subtracting multiples of the width which could happen at any resolution breaking the equals check and therefore not fixing the endless loop
image

File: src/ol/layer/Graticule.js (hunk 2 above)
Comment (mike-000) [reply src/ol/layer/Graticule.js]: Once in the renderer and once in the graticule.  Is it being done anywhere else?

Comment (ahocevar) [reply src/ol/layer/Graticule.js]: I added another commit that adds wrapX functions for extent and coordinate. With that commit, I also simplified the solution your rounding problem like I suggested.

Can you please take another final look?

Comment (mike-000) [reply src/ol/layer/Graticule.js]: The wrapX functions needed to allow `worldsAway` to be calculated when the center is at +180 otherwise the graticule loops when the view is centered on the dateline.  The strategy must test for `!equal` as any real extent change needs the graticule to be updated.  With `!containsExtent` the graticule intervals do not update when zooming it.  I cannot see any alternative to rounding as the problem is similar to JavaScript 0.2 + 0.1 and not related to resolution.

Comment (ahocevar) [reply src/ol/layer/Graticule.js]: I know that it is not *related* to resolution, but *using* resolution for rounding is nicer than arbitrary numbers. In the end what you need is pixel exact extents, and that can be achieved with rounding by resolution (i.e. 1 pixel).

File: src/ol/extent.js [hunk 3]
```diff
@@ -826,7 +826,7 @@ export function applyTransform(extent, transformFn, opt_extent, opt_stops) {
 export function wrapX(extent, projection) {
   const projectionExtent = projection.getExtent();
   const center = getCenter(extent);
-  if (projection.canWrapX() && (center[0] < projectionExtent[0] || center[0] > projectionExtent[2])) {
+  if (projection.canWrapX() && (center[0] < projectionExtent[0] || center[0] >= projectionExtent[2])) {
```
Comment (ahocevar) [inline src/ol/extent.js]: Please elaborate why you think this is necessary.

File: src/ol/layer/Graticule.js [hunk 4]
```diff
@@ -484,9 +483,11 @@ class Graticule extends VectorLayer {
     // extents may be passed in different worlds, to avoid endless loop we use only one
     const realExtent = extent.slice();
     if (this.projection_ && this.getSource().getWrapX()) {
-      wrapX(realExtent, this.projection_);
+      wrapExtentX(realExtent, this.projection_);
     }
-    if (this.loadedExtent_ && !containsExtent(bufferExtent(this.loadedExtent_, resolution / 2), realExtent)) {
+    realExtent[0] = Math.round(realExtent[0] * 1e8) / 1e8;
+    realExtent[2] = Math.round(realExtent[2] * 1e8) / 1e8;
```
Comment (ahocevar) [inline src/ol/layer/Graticule.js]:
```suggestion
    realExtent[0] = Math.round(realExtent[0] * resolution) / resolution;
    realExtent[2] = Math.round(realExtent[2] * resolution) / resolution;
```
This would round the extent to pixels, which should be accurate enough.

File: src/ol/extent.js (hunk 3 above)
Comment (mike-000) [reply src/ol/extent.js]: If you have two extents with centers at -180 and +180 they should be moved to the same real world (as +540 would be) but the with > that didn't happen, the graticule thought it had different extents and went into a loop.

File: src/ol/layer/Graticule.js [hunk 5]
```diff
@@ -484,9 +483,11 @@ class Graticule extends VectorLayer {
...
+    if (this.loadedExtent_ && !equals(this.loadedExtent_, realExtent)) {
```
Comment (ahocevar) [inline src/ol/layer/Graticule.js]:
```suggestion
    if (this.loadedExtent_ && !equals(this.loadedExtent_, realExtent.map(function(n) { return Math.round(n * resolution) / resolution; })) {
```
In combination with the above suggestion, this would round the extent to pixels, which should be accurate enough and would avoid the arbitrary `1e8` figure.

File: src/ol/coordinate.js [hunk 6]
```diff
@@ -415,7 +415,7 @@ export function toStringXY(coordinate, opt_fractionDigits) {
  */
 export function wrapX(coordinate, projection) {
   const projectionExtent = projection.getExtent();
-  if (projection.canWrapX() && (coordinate[0] < projectionExtent[0] || coordinate[0] > projectionExtent[2])) {
+  if (projection.canWrapX() && (coordinate[0] < projectionExtent[0] || coordinate[0] >= projectionExtent[2])) {
```
Comment (ahocevar) [inline src/ol/coordinate.js]: Fine for the extent's center, but here I think we do not want to include the right edge.

File: src/ol/layer/Graticule.js (hunk 5 above)
Comment (mike-000) [reply src/ol/layer/Graticule.js]: I also tried 

    if (this.loadedExtent_ && (
      !containsExtent(bufferExtent(this.loadedExtent_, resolution / 2), realExtent) ||
      !containsExtent(bufferExtent(realExtent, resolution / 2), this.loadedExtent_)
    )) {


but that fails when resolutions become so small relative to large coordinate values that buffering has no effect.

Any rounding has the potential for a different last digit.  A more general approach which would avoid that and might be useful elsewhere would be a near equality method similar to that used in the tests which checks values are within JavasScript's approx 15 digit accuracy e.g.

`Math.abs(a - b) <= Math.abs((a + b) * 1e-15)`

File: src/ol/extent.js (hunk 3 above)
Comment (ahocevar) [reply src/ol/extent.js]: Ok, thanks for the explanation. I think this fine for extent centers, but not for coordinates.

File: src/ol/layer/Graticule.js (hunk 5 above)
Comment (ahocevar) [reply src/ol/layer/Graticule.js]: What do you use to test this pull request? I.e. where do you check for the infinite loops you mentioned several times? Which example or test case?

File: src/ol/coordinate.js (hunk 6 above)
Comment (mike-000) [reply src/ol/coordinate.js]: There is a similar problem with these extents [-360, -90, 0, 90] [0, -90, 360, 90] [360, -90, 720, 90] as with the center.  They should be all produce the same real world extent but [0, -90, 360, 90] doesn't.

Comment (ahocevar) [reply src/ol/coordinate.js]: But `ol/coordinate#wrapX()` is not involved in `ol/extent#wrapX`, and also not in `ol/layer/Graticule`. So I wonder why you insist on this change in `ol/coordinate`.

Comment (ahocevar) [reply src/ol/coordinate.js]: I am fine with your change in `ol/extent#wrapX`, if that was not clear.

Comment (mike-000) [reply src/ol/coordinate.js]: `ol/coordinate#wrapX` is used in `prepareFrame` where it should be consistent with the extent

File: src/ol/layer/Graticule.js (hunk 5 above)
Comment (mike-000) [reply src/ol/layer/Graticule.js]: I set up a sandbox https://codesandbox.io/s/simple-11f0s patched with the changes and logging the extents used in the strategy function to debug the looping.  The opening at +180 problem is easily reproduced by changing `>=` to `>`  The rounding problems occur intermittently if the rounding is commented out.

File: src/ol/coordinate.js (hunk 6 above)
Comment (ahocevar) [reply src/ol/coordinate.js]: Good point.

File: src/ol/layer/Graticule.js (hunk 5 above)
Comment (ahocevar) [reply src/ol/layer/Graticule.js]: If you could turn that into a unit or rendering test, it would be great.

**Comment by ahocevar** [comment]
I think this is good now. I added an `approximatelyEquals` function for extents and had to rebase this branch because of a conflict.

Note that I set the tolerance for the `approximatelyEquals` function to the resolution (i.e. the allowed tolerance is be 1 pixel). That worked fine with your sandbox. If there are still concerns, please add tests (unit or rendering) that show the problem.

If this looks good to you now, we can merge it.

**Comment by mike-000** [comment]
All looks good.  I hadn't noticed your change to loader when I tested in the sandbox so rearranged the strategy to ensure the loader can use a simple equals comparison.
