### PR TITLE
Use drag-pan default condition with onFocusOnly

### LINKED ISSUE #11162: Rotation not working correctly in dev version
**Describe the bug**
Using alt shift drag to rotate the view in the dev version is also panning the map instead of simply rotating around the view center.

**To Reproduce**
Open https://openlayers.org/en/latest/examples/simple.html zoom in 2 levels to avoid any conflict with multiWorld: false and use alt shift drag to rotate.  The view rotates around the center as expected.  Resetting the rotation restores the view to its original setting.

Repeat with https://openlayers.org/en/master/examples/simple.htm  The view rotates apparently around a random position as it also pans.  Resetting the rotation does not restore the view to its original position.

**Expected behavior**
alt shift drag should not pan the view.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #11162.

I think the most convenient way to conditionally apply different conditions is to have a `chain(...conditions)` function. This pull request introduces such a function internally, and it also adds `onFocusOnly` options to the `DragPan` and `MousewheelZoom` interactions. This should make it easier for users to configure these interactions properly, in cases like the one described in #11102.

### CODE REVIEW

File: src/ol/events/condition.js [hunk 1]
```diff
@@ -13,6 +13,29 @@ import {assert} from '../asserts.js';
  * @typedef {function(this: ?, import("../MapBrowserEvent.js").default): boolean} Condition
  */
 
+/**
+ * Creates a condition function that is only fulfilled when a chain of conditions pass.
+ * @param {...Condition} var_args Conditions to check.
+ * @return {Condition} Condition function that checks a chain of conditions.
+ */
+export function chain(var_args) {
```
Comment (tschaub) [inline src/ol/events/condition.js:21]: If we want to make this part of the API in the future, I'd be tempted to name it `all` or `and`.
