### PR TITLE
Option to render vector layers as images

### LINKED ISSUE #5825: getStyleFunction() for ol.layer.Image ?
Hi all!

I'm using a map with a lot of different types of layer - including an ol.layer.Image for performance reasons. I prefer to style these layers with layers style function, not with per-feature styles.
Problem:
When looping over all layers the Image layer causes some problems because its interface is different from the "normal" layers.

Currently I'm using hacks like this:

``` javascript
ol.layer.Image.prototype.getStyleFunction = function() {
if (typeof this.getSource().getStyleFunction === "function") { 
        return this.getSource().getStyleFunction()
    } else {
        console.log('! This', this, 'image layer has no styled source!')
    }
}
```

The same problem occurs with getSource() - when hitting the image Layer getSource().getSource() is required.

Is there any better way to solve these problems? Or does an ol3 solution to this already exist?

Best regards
 Michael

### LINKED ISSUE #6262: ol.source.ImageVector + ol.interaction.Select toggle unselect issue
Hi,

there is a bug in ol.interraction.select combined with imagevector layer: You can normaly select by single click or add to selection, but impossible to remove from selection

step to reproduce in this jsfiddle,i juste edited the select-features example to replace ol.layer.vector with ol.layer.Image( ... new ol.source.ImageVector ... )
https://jsfiddle.net/davidhequet/ddhhtdyv/2/

1. Clic to select a feature
2. shift+click to add feature to selection
3. shift+click to remove feature from selection (wich works in standard vector layer) : nothing happens

I tried a custom toggleCondition, the selected Featurs is not detected in map.ForEachFeatureAtPixel

Thank you,
David

### LINKED ISSUE #6696: ol.interaction.Translate does not work with imageVector
vector is ok like example
http://openlayers.org/en/master/examples/translate-features.html
imageVector can't translate feature , this is demo
https://codepen.io/anon/pen/LyPqWM?editors=0010

### LINKED ISSUE #7487: imageVector geometryFunction didn't work on 4.5.0
i create a geometryFunction sample on codepan
test  v4.4.2 is ok!

v4.5.0 with image vector layer
https://codepen.io/anon/pen/XzZJby?editors=0010
image

v4.5.0 with vector layer
https://codepen.io/anon/pen/JOpjgz?editors=0010
image

v4.4.2 with image vector layer
https://codepen.io/anon/pen/BmYyoW?editors=0010
image

### PR DESCRIPTION
**Pull request by ahocevar**
This pull request deprecates `ol.source.ImageVector` and introduces a `renderMode` option for `ol.layer.Vector`. When set to `'image'`, the vector layer will be rendered as image, just like an `ol.layer.VectorTile` with `renderMode: 'image'`.

Fixes #7487.
Fixes #5825.
Fixes #6696.
Fixes #6262.

### CODE REVIEW

**Comment by ahocevar** [comment]
Note to reviewers: the actual change is in `src/ol/renderer/canvas/imagelayer.js` and pretty straightforward: The `ol.renderer.canvas.ImageLayer` renderer supports vector layers when they are configured with `renderMode: 'image'`, and the renderer looks for and creates an ol.renderer.canvas.VectorLayer renderer instance for rendering with a customized `frameState`.

File: src/ol/layer/VectorRenderType.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+goog.provide('ol.layer.VectorRenderType');
+
+/**
+ * @enum {string}
+ * Render mode for vector layers:
+ *  * `'image'`: Vector tiles are rendered as images. Great performance, but
```
Comment (bartvde) [inline src/ol/layer/VectorRenderType.js]: vector layers

File: src/ol/layer/VectorRenderType.js [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+ *    point symbols and texts are always rotated with the view and pixels are
+ *    scaled during zoom animations.
+ *  * `'vector'`: Vector tiles are rendered as vectors. Most accurate rendering
```
Comment (bartvde) [inline src/ol/layer/VectorRenderType.js]: layers

File: src/ol/renderer/webgl/imagelayer.js [hunk 3]
```diff
@@ -248,7 +247,7 @@ ol.renderer.webgl.ImageLayer.prototype.forEachLayerAtPixel = function(pixel, fra
     return undefined;
   }
 
-  if (this.getLayer().getSource() instanceof ol.source.ImageVector) {
+  if (this.getLayer().getSource().forEachFeatureAtCoordinate !== ol.nullFunction) {
     // for ImageVector sources use the original hit-detection logic,
```
Comment (bartvde) [inline src/ol/renderer/webgl/imagelayer.js]: comment also outdated since it talks about ImageVector sources

File: externs/olx.js [hunk 4]
```diff
@@ -4274,6 +4275,19 @@ olx.layer.TileOptions.prototype.zIndex;
...
 
 
+/**
+ * Render mode for vectors:
+ *  * `'image'`: Vectors are rendered as images. Great performance, but
+ *    point symbols and texts are always rotated with the view and pixels are
+ *    scaled during zoom animations.
+ *  * `'vector'`: Vectors are rendered as vectors. Most accurate rendering
+ *    even during animations, but slower performance.
+ * @type {ol.layer.VectorRenderType|string|undefined}
```
Comment (fredj) [inline externs/olx.js]: `Default is 'vector'` should be added.

File: examples/image-vector-layer.js [hunk 5]
```diff
@@ -1,38 +1,37 @@
...
 
+var style = new ol.style.Style({
+  fill: new ol.style.Fill({
+    color: 'rgba(255, 255, 255, 0.6)'
+  }),
+  stroke: new ol.style.Stroke({
+    color: '#319FD3',
+    width: 1
+  }),
+  text: new ol.style.Text()
```
[the remark this answers is not in the document]
Comment (ahocevar) [reply examples/image-vector-layer.js]: It adds a way to see how label rendering works with that mode.

File: externs/olx.js [hunk 6]
```diff
@@ -4579,7 +4594,7 @@ olx.layer.VectorTileOptions.prototype.visible;
  * @type {number|undefined}
  * @api
  */
-olx.layer.VectorOptions.prototype.zIndex;
+olx.layer.VectorTileOptions.prototype.zIndex;
```
[the remark this answers is not in the document]
Comment (ahocevar) [reply externs/olx.js]: Exactly.

**Comment by ahocevar** [comment]
Thanks for the review.
