### PR TITLE
Register and unregister events in set target handler

### LINKED ISSUE #11231: MapBrowserEventHandler needs to be destroyed for listeners to be unregistered
**Describe the bug**
`MouseWheelZoom.conditionInternal_` throws errors when the map target is null due to the `hasAttribute` check.
I see this is changed on master but I believe this bug will still exist (https://github.com/openlayers/openlayers/commit/2cac6c4f39521470a899f1c6338aa47baea05392#diff-a08a90960184e04e1b7384a480a81d6a).

**To Reproduce**
1. Go to https://codesandbox.io/s/react-openlayers-xni5f?file=/src/App.js which contains a simple map example reloading every 5s and setting the previous map target to null (`myMap.setTarget(null);`)
2. Click on the map to drag but don't release for 5s.
3. Next mouse movements will trigger an error:
image
image

What I've found so far is
- Events need a map target or they crash
- Events are not deregisterd without `map.dispose` which propagates to `disposeInternal` of `MapBrowserEventHandler` where it unlistens avoiding the events to be called.

**Expected behavior**
I am not sure which solution is preferable:
- Have events check if they have a target before checking the `hasAttribute`
- Making `map.dispose` needed for destroy (https://github.com/openlayers/openlayers/issues/10856#issuecomment-643601271 seems like it is not needed). I believe this is cleaner to avoid memory leaks everywhere. Could you tell me the reasoning to not make the dispose methods public?

Let me know what you prefer @tschaub

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #11231

This pull request moves code from the `PluggableMap` constructor and `disposeInternal()` method to the set target handler. This avoids stale event listeners when the target is changed.

### CODE REVIEW

**Comment by ahocevar** [comment]
Thanks for any review.

**Comment by EvertEt** [comment]
Updating the above codesandbox to `6.3.2-dev.1595058168339` still results in some error, will see if I can find the cause
image

I am also wondering if we call `mapBrowserEventHandler_.dispose()` during setTarget(null), shouldn't we also create it in setTarget instead of only once?

File: src/ol/PluggableMap.js [hunk 1]
```diff
@@ -1162,12 +1137,36 @@ class PluggableMap extends BaseObject {
...
+        removeEventListener(EventType.RESIZE, this.handleResize_, false);
+        this.handleResize_ = undefined;
+      }
     } else {
       targetElement.appendChild(this.viewport_);
       if (!this.renderer_) {
         this.renderer_ = this.createRenderer();
       }
 
+      const handleBrowserEvent = this.handleBrowserEvent.bind(this);
```
Comment (EvertEt) [inline src/ol/PluggableMap.js:1159]: Curious as to why we bind again instead of using `boundHandleBrowserEvent_`. Will a different bind be able to get matched over `addEventListener` and `removeEventListener`?

**Comment by ahocevar** [comment]
@EvertEt This has not been merged yet, so it won't be in the latest dev version yet.

**Comment by EvertEt** [comment]
My bad! Is it possible to test it online or should I build from this commit?

**Comment by ahocevar** [comment]
@EvertEt It's best to build from this branch.

File: src/ol/PluggableMap.js (hunk 1 above)
Comment (ahocevar) [reply src/ol/PluggableMap.js:1159]: I just realized I did not push everything I had locally. Hold on, update to come.

**Comment by ahocevar** [comment]
@EvertEt I just updated the pull request with the latest I had locally.

File: src/ol/PluggableMap.js [hunk 2]
```diff
@@ -1168,6 +1153,27 @@ class PluggableMap extends BaseObject {
         this.renderer_ = this.createRenderer();
       }
 
+      this.mapBrowserEventHandler_ = new MapBrowserEventHandler(
+        this,
+        this.moveTolerance_
+      );
+      for (const key in MapBrowserEventType) {
+        this.mapBrowserEventHandler_.addEventListener(
```
Comment (EvertEt) [inline src/ol/PluggableMap.js:1161]: Will these get removed by `this.mapBrowserEventHandler_.dispose();`? Otherwise it might cause leaks?

File: src/ol/PluggableMap.js [hunk 3]
```diff
@@ -1139,11 +1111,24 @@ class PluggableMap extends BaseObject {
...
+        EventType.CONTEXTMENU,
+        this.boundHandleBrowserEvent_
+      );
+      this.viewport_.removeEventListener(
+        EventType.WHEEL,
+        this.boundHandleBrowserEvent_
+      );
+      if (this.handleResize_ !== undefined) {
+        removeEventListener(EventType.RESIZE, this.handleResize_, false);
+        this.handleResize_ = undefined;
```
Comment (EvertEt) [inline src/ol/PluggableMap.js:1129]: Not sure if we can remove the same logic in the `(!targetElement)` branch below? I couldn't think of a case where it would still trigger. (Only 2 subsequent `setTarget(null)` but then there wouldn't be an `this.handleResize_`)

**Comment by EvertEt** [comment]
Can confirm it fixes #11231 by changing the `simple` example to include the following
```js
setTimeout(() => map.setTarget(null), 5000);
setTimeout(() => map.setTarget('map'), 7000);
```

File: src/ol/PluggableMap.js (hunk 3 above)
Comment (ahocevar) [reply src/ol/PluggableMap.js:1129]: Good catch, thanks! That was a copy/paste mistake.

File: src/ol/PluggableMap.js (hunk 2 above)
Comment (ahocevar) [reply src/ol/PluggableMap.js:1161]: Yes, these will get removed.

Comment (EvertEt) [reply src/ol/PluggableMap.js:1157]: Mind to explain me how? just interested :)
