### PR TITLE
KML string validation with extendedData

### LINKED ISSUE #9496: KML string validation with extendedData
**Describe the bug**
When creating a KML String with KML.writeFeatures(), with extendedData, the format isn't validated correctly.

**To Reproduce**
1. Create an array of features, e.g. Line with style and custom property 'lineDash'.
2. Write a KML string with:
`featString = new KML({
extractStyles: true,
defaultStyle: [kmlStyle],
}).writeFeatures(exportFeatures);`

Output:
< kml
  xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.opengis.net/kml/2.2 
  https://developers.google.com/kml/schema/kml22gx.xsd">
  < Document>
    < name>Editor< /name>
    < Placemark>
      < ExtendedData>
        < Data name="lineDash">< value>1,10</value>< /Data>
      < /ExtendedData>
      < Style>
        < LineStyle>< color>ff0000ff< /color>< width>4< /width>< /LineStyle>
      </Style>
      < LineString>
        < coordinates>
          7.969207763671874,46.941824493511206 8.666839599609375,47.246610279847005 
          8.735504150390627,47.039246258977784
        < /coordinates>
      < /LineString>
    < /Placemark>
  < /Document>
< /kml>

3. Validate the KML string against the KML schema `kml22gx.xsd` fails:
[https://developers.google.com/kml/schema/kml22gx.xsd](https://developers.google.com/kml/schema/kml22gx.xsd)

**Expected behavior**
The tag < ExtendedData > should be located after the <Style> tag in the KML string.

### PR DESCRIPTION
**Pull request by edellucien**
Pull Request to face issue:
Fix #9496

### CODE REVIEW

File: src/ol/format/KML.js [hunk 1]
```diff
@@ -2713,6 +2703,18 @@ function writePlacemark(node, feature, objectStack) {
   pushSerializeAndPop(context, PLACEMARK_SERIALIZERS,
     OBJECT_PROPERTY_NODE_FACTORY, values, objectStack, orderedKeys);
 
+  properties = feature.getProperties();
```
Comment (ahocevar) [inline src/ol/format/KML.js]: Instead of reading the properties again here, you could keep the order as it was, and only call `pushSerializeAndPop(context, PLACEMARK_SERIALIZERS, EXTENDEDDATA_NODE_FACTORY, [namesAndValues], objectStack)` here instead of above.

Comment (ahocevar) [reply src/ol/format/KML.js]: Thanks for your work on this! It would be great if you could address the above comment.

Comment (edellucien) [reply src/ol/format/KML.js]: Thanks for the review and the reactivity! :smile:
