### PR TITLE
Fix decluttering opacity, zIndex and circles

### LINKED ISSUE #15611: setOpacity on Vector Layer with 'declutter' set causes layer to disappear.
**Describe the bug**
This one has me a bit stumped!

As of v9.0 calling setOpacity on a VectorLayer when `declutter` is enabled causes that layer to disappear.

**To Reproduce**
Steps to reproduce the behavior
(Apologies for not linking directly to an example as CodeSandbox won't let users create their own drafts anymore without paying)

1. Go to https://openlayers.org/en/latest/examples/vector-labels.html
2. Edit codesandbox example to add `declutter: true` to vectorPoints layer definition (or seemingly to *any* vector layer defined also causes the issue). Then add the following at the end of the example code:
```js
 setTimeout(() => {
  vectorPoints.setOpacity(0.5);
}, 2000);
```
3. Run example, and watch vectorPoints layer disappear after 2 seconds when `setOpacity` is called

**Expected behavior**
The layer to correctly update it's opacity without vanishing

### PR DESCRIPTION
**Pull request by ahocevar**
Working on a fix for #15611 (point symbols disappearing on vector layers with opacity != 1) I created a new rendering test, which revealed two more issues:
* `Circle` geometries are not rendered when decluttering
* Styles with negative `zIndex` are rendered *after* styles with positive `zIndex`.

All these are fixed now.

Fixes #15611.

### CODE REVIEW

File: src/ol/render/canvas/ExecutorGroup.js [hunk 1]
```diff
@@ -426,8 +426,9 @@ class ExecutorGroup {
 
   renderDeferred() {
     const deferredZIndexContexts = this.deferredZIndexContexts_;
-    for (const key in deferredZIndexContexts) {
-      deferredZIndexContexts[key].forEach((zIndexContext) => {
+    const zs = Object.keys(deferredZIndexContexts).sort(ascending);
+    for (let i = 0, ii = zs.length; i < ii; ++i) {
+      deferredZIndexContexts[zs[i]].forEach((zIndexContext) => {
```
Comment (ahocevar) [inline src/ol/render/canvas/ExecutorGroup.js:431]: Sorting makes sure that styles with negative zIndex will be rendered before styles with positive zIndex.

File: src/ol/renderer/vector.js [hunk 2]
```diff
@@ -70,14 +70,15 @@ export function getTolerance(resolution, pixelRatio) {
...
  */
-function renderCircleGeometry(builderGroup, geometry, style, feature) {
+function renderCircleGeometry(builderGroup, geometry, style, feature, index) {
   const fillStyle = style.getFill();
   const strokeStyle = style.getStroke();
   if (fillStyle || strokeStyle) {
     const circleReplay = builderGroup.getBuilder(style.getZIndex(), 'Circle');
     circleReplay.setFillStrokeStyle(fillStyle, strokeStyle);
-    circleReplay.drawCircle(geometry, feature);
+    circleReplay.drawCircle(geometry, feature, index);
```
Comment (ahocevar) [inline src/ol/renderer/vector.js:81]: The missing `index` here was the reason for circles not being rendered, because their order index ended up being `undefined`.

File: src/ol/render/canvas/ExecutorGroup.js (hunk 1 above)
Comment (tschaub) [reply src/ol/render/canvas/ExecutorGroup.js:431]: Do we care that a z-index of `-10` will be sorted before `-2` (and `10` before `2`)?

Comment (ahocevar) [reply src/ol/render/canvas/ExecutorGroup.js]: Oh, thanks for spotting this. I just committed a fix.

**Review by tschaub — APPROVED** [review]
