### PR TITLE
Document events fired by interactions

### LINKED ISSUE #9471: Event name documentation missing
**Describe the bug**
In the api documentation the names of special events do not appear.

**To Reproduce**
See for example https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html
under `Fires:` only the type of the event is shown (`DrawEvent`) but not the names. (`drawstart` and `drawend`)

**Expected behavior**
Like with the generic `change` events this should appear as: `drawstart (DrawEvent)`

### PR DESCRIPTION
**Pull request by tschaub**
The event names for our interactions are not currently showing up in the docs.  It looks like the `longname` for these doclets is not being generated correctly if the `@event` annotation doesn't have the full module path.

~~It feels like there should be an opportunity to fix this another way (supporting the existing syntax).  I'll keep digging to see where that `longname` is generated - but I think this is an ok change to merge in too~~.

**Update**: I updated this branch to pull in the changes from openlayers/jsdoc-plugin-typescript#5

Here is what the draw interaction docs look like after this change:
image

Fixes #9471

### CODE REVIEW

File: src/ol/interaction/Extent.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ import {createEditingStyle} from '../style/Style.js';
 const ExtentEventType = {
   /**
    * Triggered after the extent is changed
-   * @event ExtentEventType#extentchanged
+   * @event module:ol/interaction/Extent~ExtentEvent#extentchanged
```
Comment (tschaub) [inline src/ol/interaction/Extent.js]: Even if we do make another change to address the `longname` generation, we need to make a change here too.  We want the docs pointing to `ExtentEvent` instead of `ExtentEventType`.

**Comment by tschaub** [comment]
It looks like this might be the code that is supposed to be generating full module longnames:

https://github.com/openlayers/jsdoc-plugin-typescript/blob/a2c2c3e5fd12653038681da85f4afcc15ee51971/index.js#L201-L215

**Comment by tschaub** [comment]
See openlayers/jsdoc-plugin-typescript#5 for a change in the plugin package.  After that is published, I can update this branch to pull in the new version and make the one additional change mentioned above (https://github.com/openlayers/openlayers/pull/9476#pullrequestreview-231487224).

File: src/ol/interaction/Extent.js (hunk 1 above)
Comment (tschaub) [reply src/ol/interaction/Extent.js]: Addressed in 9c6dbe5a339744e990bbb85c775515de6cf8bebb.
