### PR TITLE
Avoid page scrolling when freehand drawing on mobile

### LINKED ISSUE #10804: Freehand drawing on map ends by itself after start drawing.
**Describe the bug**
Freehand drawing on map ends by itself after start drawing.

**To Reproduce**
1. https://openlayers.org/en/latest/examples/draw-freehand.html?q=draw
2. go in developer tools, mobile view
3. try to draw

**Expected behavior**
it should stop drawing when touch is done.

I already found a way to fix this issue:
touch-action: None;
seems to be removed in mobile view.

### PR DESCRIPTION
**Pull request by ahocevar**
Fixes #10804.

### CODE REVIEW

File: src/ol/interaction/Draw.js [hunk 1]
```diff
@@ -523,7 +523,11 @@ class Draw extends PointerInteraction {
     } else if (move) {
       pass = event.type === MapBrowserEventType.POINTERMOVE;
       if (pass && this.freehand_) {
-        pass = this.handlePointerMove_(event);
+        this.handlePointerMove_(event);
+        if (this.shouldHandle_) {
```
Comment (tschaub) [inline src/ol/interaction/Draw.js:527]: Are there cases where `this.shouldHandle_` is true and `this.handlePointerMove_` wasn’t returning `false`?

Comment (ahocevar) [reply src/ol/interaction/Draw.js:527]: `this.handlePointerMove` always returned true, so I removed the return.
