### PR TITLE
Make KML point feature styles compatible with declutter

### LINKED ISSUE #10540: KML features flicker when decluttering is enabled
**Describe the bug**
KML features and labels flicker when decluttering is enabled and are not always visible. 

**To Reproduce**
1. Add KML layer to the map (Use attached KML sample)
2. Zoom into the layer area 
3. KML features flicker and are not always visible

**Expected behavior**
KML features do not flicker and are visible

Here is a sample:
`import 'ol/ol.css';
import {Map, View} from 'ol';
import {Tile as TileLayer, Vector as VectorLayer} from 'ol/layer.js';
import {OSM, Vector as VectorSource} from 'ol/source.js';
import KML from 'ol/format/KML.js';

let vectorLayer = new VectorLayer({
    source: new VectorSource({
        url: 'sample.kml',
        format: new KML()
    }),
    declutter: true
});

const map = new Map({
    target: 'map',
    layers: [
        new TileLayer({
            source: new OSM()
        }),
        vectorLayer
    ],
    view: new View({
        center: [0, 0],
        zoom: 0
    })
});`

[sample.zip](https://github.com/openlayers/openlayers/files/4076957/sample.zip)

### LINKED ISSUE #10546: Character codes appearing in labels
**Describe the bug**

image

Although the name is **Andy&amp;apos;s** in the data it should be decoded in the label.

This is from a KML example but I presume it could happen in any XML based format.  Would it be acceptable if either `ol/style/Text` or the renderer routinely called `decodeURIComponent()` on the supplied text or should it be the responsibility of the parser?

### PR DESCRIPTION
**Pull request by mike-000**
Fixes #10540
Fixes #10546

Fixes images or labels not visible (flickering is a general issue with any decluttering).

Return a single style object for image and text for point features as concatenating two styles in an array is not compatible with decluttering

Update expected result of test to single style object to reflect this change
Remove a duplicated test

Also convert any html character codes in labels and include example in test

### CODE REVIEW

File: src/ol/format/KML.js [hunk 1]
```diff
@@ -949,26 +946,29 @@ function createFeatureStyleFunction(style, styleUrl, defaultStyle, sharedStyles,
       if (drawName) {
         name = /** @type {string} */ (feature.get('name'));
         drawName = drawName && !!name;
+        // convert any html character codes
+        if (drawName && name.search(/&[^&]+;/) > -1) {
+          const text = document.createElement('textarea');
```
Comment (ahocevar) [inline src/ol/format/KML.js]: In terms of performance, it would be better to create this `textarea` only once and reuse it.

Comment (mike-000) [reply src/ol/format/KML.js]: Yes, I've updated it.
